folio-org/mod-data-export

pom.xml
src/main/java/org/folio/config/ApplicationConfig.java
src/main/java/org/folio/dao/FileDefinitionDao.java
src/main/java/org/folio/dao/impl/FileDefinitionDaoImpl.java
src/main/java/org/folio/rest/impl/ModTenantAPI.java
src/main/java/org/folio/service/cleanup/StorageCleanupService.java
src/main/java/org/folio/service/cleanup/StorageCleanupServiceImpl.java
src/main/java/org/folio/service/upload/storage/FileStorage.java
src/main/java/org/folio/service/upload/storage/LocalFileSystemStorage.java
src/test/java/org/folio/rest/RestVerticleTestBase.java
src/test/java/org/folio/service/ApplicationTestConfig.java
src/test/java/org/folio/service/cleanup/StorageCleanupServiceImplTest.java

To have the ability to remove an old files by the system automatically.
See a similar approach on the pull request
1. Create Vertx periodic job (1 time per hour)
2. Initialize the job ModTenantAPI
3. Create interface and implementation to look up for old FileDefinitions and remove related files at the file system calling FileStorageService.deleteFile
1. Created StorageCleanupService
2. Covered with tests
3. Verified on reference env

MDEXP-49 StorageCleanupService: ability to clear up file storage

---

src/main/java/org/folio/rest/impl/InitAPIImpl.java

Purpose
* At this moment ExportManager and InputDataManager transfer data with each other directly, using created instances. We should enable data-transfer based on an event bus.
https://vertx.io/docs/vertx-service-proxy/java/
Approach
* Update InitApi: initialize(Vertx.createProxy) and use generated proxies instead of component instances

Mdexp 58 - bugfix

---

NEWS.md
pom.xml

Release the mod-data-export
Follow the official procedure for maven-based modules https://dev.folio.org/guidelines/release-procedures/#maven-based-modules
Also, see very helpful notes https://wiki.folio.org/display/FOLIJET/Acquisitions+-+Release+Procedures

MDEXP-64: Mod-data-export release v1.0.0

---

src/main/java/org/folio/rest/exceptions/ServiceException.java
src/main/java/org/folio/rest/impl/DataExportImplFileDefinitionImpl.java
src/main/java/org/folio/util/ErrorCode.java
src/test/java/org/folio/rest/impl/FileUploadServiceTest.java

Currently the validation happens on the UI but the validation should occur on the backend as well in order to prevent any malicious files being uploaded.
- validation only for /data-export/fileDefinitions
- Support .csv extension
- API tests are added

MDEXP-74 Add file extenstion valiation to /data-export/fileDefinitions

---

src/main/java/org/folio/service/manager/export/ExportManagerImpl.java
src/test/java/org/folio/service/manager/export/ExportManagerUnitTest.java

It appears Dmitro didn't check how SRS returns records if to request 15 entries in one batch. So SRS returns first 10 records for the given 15 UUIDs :) Andrey has tested this fix locally using 100 UUIDs, it works.
Decrease number of UUIDs in from 15 to 10
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment.  Communication is paramount …

MDEXP-91 In large data exports - not all records are being exported

---

src/main/java/org/folio/rest/impl/DataExportHelper.java
src/main/java/org/folio/service/job/JobExecutionService.java
src/main/java/org/folio/service/job/JobExecutionServiceImpl.java
src/main/java/org/folio/service/manager/input/InputDataManagerImpl.java
src/test/java/org/folio/rest/impl/DataExportHelperTest.java
src/test/java/org/folio/rest/impl/EndToEndTest.java
src/test/java/org/folio/service/job/JobExecutionServiceUnitTest.java
src/test/java/org/folio/service/manager/input/InputDataManagerUnitTest.java

https://issues.folio.org/browse/MDEXP-92
- In the naming of the file generated by export, HRID is used instead of timestamp.

MDEXP-92 Change naming of the file generated by export

---

descriptors/ModuleDescriptor-template.json

We are using an incorrect permission name for fetching inventory instances
- correct permission name to inventory-storage.instances.collection.get …

MDEXP-135: correcting permission name for inventory storage

---

src/main/java/org/folio/service/mapping/processor/RuleFactory.java

Fix for the issue - rules that generated by mapping profile transformations are appended to list of default rules each time when called RuleFactory.create method with not empty mapping profile transformations. Fix includes appending default rules and transformation rules to a new list instead of appending to list of default rules …

MDEXP-162 Fix accumulation of default rules with mapping profile transformations

---

src/main/resources/templates/db_scripts/schema.json

https://issues.folio.org/browse/MDEXP-200
Need to have proper fromModuleVersion for job_execution table as the foreign key constraint was added
TODO

MDEXP-200- adding proper schema version

---

src/main/java/org/folio/service/manager/export/ExportManagerImpl.java

https://issues.folio.org/browse/MDEXP-203
The issue relates to the situation when all UUIDs in the csv file to export is invalid(no records in srs or instances in inventory).
In such case, in the last chunk of data, we will not increment the progress bar. Added changes to increment progress bar even if export result is failed. …

MDEXP-203 Fix incorrect number of failed exported records

---

src/main/resources/rules/rulesDefault.json

https://issues.folio.org/browse/MDEXP-214
Fields 110 and 111 are having incorrect first indicator
change the default rules to add correct indicator …

MDEXP-214: Update indicator 1 for 110,111 fields

---

descriptors/ModuleDescriptor-template.json
src/main/java/org/folio/clients/InventoryClient.java
src/main/java/org/folio/service/mapping/TranslationsFunctionHolder.java
src/main/java/org/folio/service/mapping/referencedata/ReferenceDataImpl.java
src/main/java/org/folio/service/mapping/referencedata/ReferenceDataProvider.java
src/main/java/org/folio/util/ExternalPathResolver.java
src/main/resources/rules/rulesDefault.json
src/test/java/org/folio/clients/InventoryClientUnitTest.java
src/test/java/org/folio/rest/MockServer.java
src/test/java/org/folio/rest/impl/DataExportTest.java
src/test/java/org/folio/service/mapping/MappingServiceUnitTest.java
src/test/java/org/folio/service/mapping/TranslationFunctionHolderUnitTest.java
src/test/resources/mapping/expected_marc.json
src/test/resources/mapping/expected_marc_record_with_holdings_and_items.json
src/test/resources/mapping/given_inventory_instance.json
src/test/resources/mockData/inventory/get_electronic_access_relationships_response.json

FOLIO inventory instance contains electronic access element that will need to be mapped to the specific MARC fields while generating a record on the fly.
Added a new rule to rulesDefault.json file with fieldId "865" and four subfields for instance electronic access fields. At the same time, this rule contains a specific data source for the second indicator. It has a translation function "set_electronic_access_indicator" and a set of parameters with electronic access relationship values and corresponding indicator values. In case if an electronic access JSON object doesn't contain relashionshipId corresponding to any of parameter key then translation function returns an empty indicator value.
- Does …

MDEXP-183 Generate MARC bib record - Instance electronic access

---

src/main/resources/templates/db_scripts/default_data/create_default_job_profile.sql
src/main/resources/templates/db_scripts/default_data/create_default_mapping_profile.sql
src/main/resources/templates/db_scripts/schema.json

https://issues.folio.org/browse/MDEXP-253
After changing the mechanism of adding default profiles from API calls to DB scripts, we should add metadata to our default profiles data(previously it was created by RMB when we called our API to create profiles). …

MDEXP-253-Fix-Metadata Fix data Migration issue on goldenrod

---

src/main/java/org/folio/rest/impl/DataExportImplMappingProfilesImpl.java
src/main/java/org/folio/service/profiles/jobprofile/JobProfileServiceImpl.java
src/main/java/org/folio/service/profiles/mappingprofile/MappingProfileService.java
src/main/java/org/folio/service/profiles/mappingprofile/MappingProfileServiceImpl.java
src/test/java/org/folio/service/profiles/JobProfileServiceUnitTest.java
src/test/java/org/folio/service/profiles/MappingProfileServiceUnitTest.java

https://issues.folio.org/browse/MDEXP-225
The purpose is to do not allow a user to delete&edit default profiles 
Verify the id of the incoming profile, if it's default id, then throw an exception.  …

MDEXP-225 Restrict deletion of default mapping profile and job profile

---

src/main/java/org/folio/service/mapping/referencedata/ReferenceDataImpl.java
src/main/java/org/folio/service/transformationfields/TransformationFieldsConfig.java
src/main/java/org/folio/service/transformationfields/TransformationFieldsServiceImpl.java
src/main/java/org/folio/util/ExternalPathResolver.java
src/test/java/org/folio/rest/impl/TransformationFieldsServiceTest.java
src/test/resources/mapping/expectedTransformationFields.json

https://issues.folio.org/browse/MDEXP-271
For proper translations, the UI needs a way to differentiate default values with values that they have to replace with reference data.This PR addresses that
Add default at the end of default field names
Additional:
- This also has a fix for the comment which was missed in https://github.com/folio-org/mod-data-export/pull/146#discussion_r474689945
Ideally all of the PRs …

MDEXP-271: Adding default in display name

---

src/test/java/org/folio/service/mapping/MappingServiceUnitTest.java
src/test/java/org/folio/service/mapping/convertor/SrsRecordConvertorServiceUnitTest.java
src/test/resources/mapping/expected_marc_record_with_only_holdings_and_items.json
src/test/resources/mapping/expected_marc_record_with_only_holdings_and_items_and_instances.json

Temporary fix to remove usage of the old location transformations as far as the old location translation function was removed from generate-marc-utils library. Removed location fields from unit test, nevertheless they will be returned in the scope of full PR for MDEXP-252 with a new convention of naming and so on.

Fix after removing old location function in gererate-marc-utils

---

README.md

https://issues.folio.org/browse/MDEXP-236
I used this instruction for setting up the java profiler - https://wiki.folio.org/pages/viewpage.action?pageId=25724828.
Created 1million records in inventory and SRS. Exported it with the default profile 3 times and get an average result.
Then  I created 1 million instances, each of them has 1 holding, and each holding has 1 item, and used the custom profile 3 times, and gets the average result.
How to set up java profiler -  https://wiki.folio.org/pages/viewpage.action?pageId=25724828

MDEXP-236 Check how much memory the module needs to get generated 1 file

---

pom.xml
src/main/resources/templates/db_scripts/migration_scripts/add_last_updated_date_to_job.sql
src/main/resources/templates/db_scripts/migration_scripts/rename_job_statuses.sql

https://issues.folio.org/browse/MDEXP-306
Fix migration scripts to run on latest version
Fix them to run on any tenant
- Add conditions to check if the job is in failed status to change to FAIL
- replace diku with generic name
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment.  Communication is paramount if that is to be achieved, …

MDEXP-306: fixing migration scripts

---

src/main/java/org/folio/service/file/reader/LocalStorageCsvSourceReader.java
src/main/java/org/folio/service/file/upload/FileUploadServiceImpl.java
src/main/java/org/folio/service/job/JobExecutionServiceImpl.java
src/main/java/org/folio/service/manager/input/InputDataManagerImpl.java
src/test/java/org/folio/rest/impl/DataExportTest.java
src/test/java/org/folio/rest/impl/EndToEndTest.java
src/test/java/org/folio/rest/impl/JobExecutionServiceTest.java

###**PURPOSE**
Add progress object to jobExecution when uploading an empty file.
Jira: https://issues.folio.org/browse/MDEXP-267

MDEXP-267: add progress object to jobExecution when uploading an empty file

---

src/main/java/org/folio/rest/impl/DataExportImplMappingProfilesImpl.java
src/main/java/org/folio/service/profiles/mappingprofile/MappingProfileService.java
src/main/java/org/folio/service/profiles/mappingprofile/MappingProfileServiceImpl.java
src/test/java/org/folio/rest/impl/DataExportTest.java
src/test/java/org/folio/rest/impl/MappingProfileServiceTest.java
src/test/java/org/folio/rest/impl/RestVerticleTestBase.java
src/test/java/org/folio/service/profiles/MappingProfileServiceUnitTest.java
src/test/resources/endToEndTestFiles/mappingProfile.json
src/test/resources/profiles/mappingProfile.json

https://issues.folio.org/browse/MDEXP-276
##Description
Add validation for transformations during creation and updating mapping profile, match transformation fieldId with existing transformationFields …

MDEXP-276 Restrict creating a mapping profile to supported fields only

---

pom.xml
src/main/java/org/folio/service/job/JobExecutionService.java
src/main/java/org/folio/service/job/JobExecutionServiceImpl.java
src/main/java/org/folio/service/manager/input/InputDataManagerImpl.java
src/test/java/org/folio/rest/impl/DataExportTest.java
src/test/java/org/folio/rest/impl/JobExecutionServiceTest.java
src/test/java/org/folio/service/manager/input/InputDataManagerUnitTest.java

Add fileName and runBy fields to jobExecution when uploading an empty file for borh csv and cql upload formats.
Jira: https://issues.folio.org/browse/MDEXP-267

MDEXP-267: fix jobExecution empty fileName and runBy when uploading an empty file.

---

.rancher-pipeline.yml
descriptors/ModuleDescriptor-template.json
ramls/dataExport.raml
src/main/java/org/folio/rest/impl/DataExportImpl.java
src/main/java/org/folio/rest/impl/ModTenantAPI.java
src/main/java/org/folio/service/file/cleanup/StorageCleanupServiceImpl.java
src/test/java/org/folio/rest/impl/DataExportCleanUpFilesTest.java
src/test/java/org/folio/rest/impl/ErrorLogsTest.java
src/test/java/org/folio/rest/impl/RestVerticleTestBase.java
src/test/java/org/folio/rest/impl/StorageTestSuite.java

https://issues.folio.org/browse/MDEXP-305
While investigating the issue, I saw that it is unreproducible on test/scratch envs. Investigated logs from bugfest-goldenroad, no logs about cleanup process - so the cleanup job is not running at all, or stuck. 
Decided to change mechanism of the cleanup process to provide a new endpoint, and use okapi timer to retrieve this API.
Also, it will give us the opportunity to manually start the cleanup process.
Updated rancher configs to helm configs with version: 0.1.30

MDEXP-305 Fix generated mrc files and directories are not being deleted

---

src/main/java/org/folio/service/file/reader/LocalStorageCsvSourceReader.java
src/main/java/org/folio/service/logs/ErrorLogService.java
src/main/java/org/folio/service/logs/ErrorLogServiceImpl.java
src/main/java/org/folio/service/manager/input/InputDataManagerImpl.java
src/main/java/org/folio/util/ErrorCode.java
src/main/java/org/folio/util/HelperUtils.java
src/test/java/org/folio/rest/impl/DataExportTest.java
src/test/java/org/folio/service/manager/input/InputDataManagerUnitTest.java

When the random UUIDs not in the last batch - then job execution status always completed, instead of completed with errors.
Also, if the CSV file contains some text, not UUIDs, status should be completed with errors too.
After calling finalize export, check if the error logs related to UUIDs are present, if yes - status completed with errors, if not - completed.

MDEXP-337 Fix correct job status when random uuids not in last batch

---

src/main/java/org/folio/service/manager/input/InputDataManagerImpl.java
src/main/java/org/folio/util/ErrorCode.java
src/test/java/org/folio/service/manager/input/InputDataManagerUnitTest.java

https://issues.folio.org/browse/MDEXP-338
Sometimes, while uploading an empty file, the job execution state could be wrong, some fields will be missing.
waiting when preparejobForExport will be finishing before export next chunk.

MDEXP-338 Fix periodically wrong jobExecution state when uploading an empty file

---

ramls/samples/logs/recordLog.sample
ramls/schemas/logs/recordLog.json
src/main/java/org/folio/clients/ConfigurationsClient.java
src/main/java/org/folio/config/ApplicationConfig.java
src/main/java/org/folio/service/logs/AffectedRecordBuilder.java
src/main/java/org/folio/service/logs/AffectedRecordHoldingBuilder.java
src/main/java/org/folio/service/logs/AffectedRecordInstanceBuilder.java
src/main/java/org/folio/service/logs/AffectedRecordItemBuilder.java
src/main/java/org/folio/service/logs/ErrorLogService.java
src/main/java/org/folio/service/logs/ErrorLogServiceImpl.java
src/main/java/org/folio/service/manager/input/InputDataManagerImpl.java
src/main/java/org/folio/service/mapping/MappingServiceImpl.java
src/main/java/org/folio/util/ErrorCode.java
src/test/java/org/folio/rest/impl/ConfigurationsClientTest.java
src/test/java/org/folio/rest/impl/DataExportTest.java
src/test/java/org/folio/rest/impl/MockServer.java
src/test/java/org/folio/service/ApplicationTestConfig.java
src/test/java/org/folio/service/logs/ErrorLogServiceUnitTest.java
src/test/java/org/folio/service/logs/builder/AffectedRecordHoldingBuilderUnitTest.java
src/test/java/org/folio/service/logs/builder/AffectedRecordInstanceBuilderUnitTest.java
src/test/java/org/folio/service/logs/builder/AffectedRecordItemBuilderUnitTest.java
src/test/java/org/folio/service/mapping/MappingServiceUnitTest.java
src/test/resources/mapping/given_InstanceHoldingsItems.json
src/test/resources/mapping/given_small_instance.json
src/test/resources/mapping/given_small_instanceHolding.json
src/test/resources/mockData/configurations/get_host_configuration_response.json

https://issues.folio.org/browse/MDEXP-262
Create a link to the inventory record if the export fails
Get host from mod config, created a new field inventoryRecordLink  in the affected record.
Build proper affected record instead of instance is always at the top:
if instance record affected, no related holdings and items, if holding - related instance is present, if item - related holding and instance is present. …

MDEXP-262 Create a link to the inventory record if the export fails

---

src/main/java/org/folio/service/export/LocalFileSystemExportService.java
src/test/java/org/folio/service/export/ExportServiceUnitTest.java

https://issues.folio.org/browse/MDEXP-351
Add check to not store file if data is empty during export inventory||srs records. We will avoid creating a file and storing it in S3
with empty data. 
Related PR: https://github.com/folio-org/generate-marc-utils/pull/29

MDEXP-351 Add check to not store MARC record in file if data is empty

---

descriptors/ModuleDescriptor-template.json
src/main/java/org/folio/clients/InventoryClient.java
src/main/java/org/folio/util/ExternalPathResolver.java
src/test/java/org/folio/rest/impl/MockServer.java

https://issues.folio.org/browse/MODINVSTOR-626
Update interface and uri to use record-bulk endpoint instead of instance-bulk.
This PR should be merged together with https://github.com/folio-org/mod-inventory-storage/pull/556 and https://issues.folio.org/browse/UIIN-1368

MODINVSTOR-626 Update interface for bulk endpoint

---

src/test/java/org/folio/rest/impl/StorageCleanupServiceImplTest.java

https://issues.folio.org/browse/MDEXP-343
Randomly failing tests on the StorageCleanupServiceImplTest class
- The tests were returning a new future rather than the completed future from the clean storage step
This might be a possible fix as we were not able to replicate the issue consistently
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing …

MDEXP-343 - Fix intermittent unit test failures

---

ramls/dataExport.raml
ramls/samples/quickExportResponse.sample
ramls/schemas/quickExportRequest.json
ramls/schemas/quickExportResponse.json
src/main/java/org/folio/rest/impl/DataExportImpl.java
src/main/java/org/folio/service/file/definition/FileDefinitionService.java
src/main/java/org/folio/service/file/definition/FileDefinitionServiceImpl.java
src/test/java/org/folio/rest/impl/DataExportTest.java

https://issues.folio.org/browse/MDEXP-349
1. Return a 200 response that includes the jobExecutionId and jobExecution.hrid in the body;
2.  Add an optional `fileName` key to the request body. If fileName is not present, the default  **quick-export-HRID** name will be used

MDEXP-349 Change quick export endpoint to return jobExecution id and hrId, add fileName to request

---

pom.xml

https://issues.folio.org/browse/MDEXP-364
Update to relesed version on generate-marc-utils 1.1.0 that possible can fix the issue MDEXP-364
While it's …

Update generate-marc-utils verison to 1.1.0

---

NEWS.md
descriptors/ModuleDescriptor-template.json
pom.xml

https://issues.folio.org/browse/MDEXP-371 
Major Iris release which includes below features :
* allow a user to append holdings and item data with MARC bib record when the user wants to export the record from SRS
* improve validation for mapping profile transformations: add general backend validation during saving; allow to pass transformations with empty value; allow characters in indicator fields  
* improve error logs: reflect in error logs what record exactly leads to the exception during the export and append exactly the field name that causes the error; append a link to the inventory record if the export fails
* add a quick export feature: provide an endpoint to trigger the export based on a provided list of identifiers or CQL statement and can be used in triggering exports by …

MDEXP-371 - Release 4.0.0

---

NEWS.md
descriptors/ModuleDescriptor-template.json
pom.xml

https://issues.folio.org/browse/MDEXP-389
This bugfix release includes fix for inconsistent results when holdings and items data incorrectly appended to the srs record
in MARC file.
[Full Changelog](https://github.com/folio-org/mod-data-export/compare/v4.0.0...v4.0.1)
* [MDEXP-385](https://issues.folio.org/browse/MDEXP-385) - Holdings and items data incorrectly appended to the srs record

MDEXP-389 Release 4.0.1

---

descriptors/ModuleDescriptor-template.json
src/test/resources/mockData/inventory/get_instance_response_in000005.json
src/test/resources/mockData/inventory/holdings_in000005.json
src/test/resources/mockData/inventory/holdings_in00041.json
src/test/resources/mockData/inventory/items_in000005.json
src/test/resources/mockData/inventory/items_in00041.json

Allow additional versions for required inventory interfaces:
* instance-storage 8.0
* holdings-storage 4.0
* item-storage 9.0
They add the `_version` property for optimistic locking.
mod-data-export only uses GET APIs from inventory.
No mod-data-export interfaces are changed.
Unit tests are extended to show that mod-data-export
can process the `_version` property.

MDEXP-403: Inventory interface versions optimistic locking

---

src/main/resources/templates/db_scripts/migration_scripts/change_progress_total_data_type.sql

Jira: https://issues.folio.org/browse/MDEXP-402
Enhance migration script with additional checks that nested 'progress' object is not empty and populate existed empty 'progress' objects with 0 values for all possible nested fields like total, failed, and exported. Cover the case where only the 'exported' field is presented and populate such 'progress' objects with total field = exported field value and failed = 0.

MDEXP-402: Migration Script does not handle all cases

---

src/test/java/org/folio/service/mapping/RuleFactoryUnitTest.java

Jira: https://issues.folio.org/browse/MDEXP-398
Add coverage for lines in TransformationRuleBuilder class. 
The Jira was created a long time ago and the sonar shows coverage on new code only for the last 30 days, therefore the information about which lines exactly should have been covered was lost, I analyzed the merged pull-request within these 30 days and find the PR where the changes have been done regarding MappingService(92.2% coverage) and TransformationRuleBuilder(83.3% coverage). I found a place that wasn't covered and added a unit test for that in the scope of this PR.

MDEXP-398: Improve code coverage on new code

---

src/main/java/org/folio/service/file/storage/LocalFileSystemStorage.java

Jira: https://issues.folio.org/browse/MDEXP-394
Try to complete the promise of the blocking code handler. This promise object wasn't completed which may cause objects to stuck in the memory cause they hold by the handler which cannot be finished.

MDEXP-394: Memory leaks in mod-data-export

---

src/main/java/org/folio/service/export/ExportService.java
src/main/java/org/folio/service/export/LocalFileSystemExportService.java
src/main/java/org/folio/service/manager/export/strategy/InstanceExportStrategyImpl.java
src/main/java/org/folio/service/mapping/converter/SrsRecordConverterService.java
src/main/java/org/folio/util/ErrorCode.java
src/test/java/org/folio/service/export/ExportServiceUnitTest.java
src/test/java/org/folio/service/manager/export/InstanceExportStrategyUnitTest.java

Jira: https://issues.folio.org/browse/MDEXP-422
During the testing, I noticed that the job status was incorrect when there was a mixed set of records with records that should be exported and records that should fail. As well the failed/exported fields of the job progress were incorrect in the case of mixed records.
Update the unit tests.
The flow will be covered with integration tests in https://github.com/folio-org/folio-integration-tests. Unit tests are not applicable here.
In order to make the job display a correct status, the ERROR_MARC_RECORD_CANNOT_BE_CONVERTED code was added to the `isSelectedErrorsPresent()` method which tracks the error logs related to the export and if some are presented then the job obtains the COMPLETED WITH ERRORS status instead of the just COMPLETED.
Since …

MDEXP-422: Gracefully handle MARC records that exceed the size limit

---

src/main/java/org/folio/clients/InventoryClient.java
src/main/java/org/folio/config/ApplicationConfig.java
src/main/java/org/folio/service/file/upload/FileUploadServiceImpl.java
src/test/java/org/folio/rest/impl/InventoryClientTest.java
src/test/java/org/folio/rest/impl/MockServer.java
src/test/java/org/folio/service/file/upload/FileUploadServiceUnitTest.java

Jira: https://issues.folio.org/browse/MDEXP-425
Avoid spamming of ThreadBlockedEception when the inventory request takes more than 60 seconds to be processed.  
Refactor client to make it async and replace the verx.executeBlocking with a simple call to this new async method form.  
I tested the approach, it works fine.

MDEXP-425: When a highly inefficient query is done, vertx main thread is blocked 

---

pom.xml

[MDEXP-429](https://issues.folio.org/browse/MDEXP-429) - Update generate-marc-utils version to 1.2.0-SNAPSHOT
Use current version of generate-marc-utils. …

MDEXP-429 - Update generate-marc-utils version

---

src/main/java/org/folio/service/export/LocalFileSystemExportService.java
src/test/java/org/folio/service/export/ExportServiceUnitTest.java

[MDEXP-426](https://issues.folio.org/browse/MDEXP-426) - Escape control characters in quoted literals
Handle error gracefully if SRS record contains not escaped control characters (for example, \007).
- handle json parse unchecked exception when parser encounters with control character
- add test case
Control characters like \007 cannot be added to SRS record in the database, so that this case should be tested only through the changes directly in the code.
- Are the JIRAs under active …

MDEXP-426 - Escape control characters in quoted literals

---

src/main/java/org/folio/clients/InventoryClient.java

Jira: https://issues.folio.org/browse/MDEXP-440
Increase limit param from 200 to 1000 which is a FOLIO default limit param(for instance the setting apps and others use the limit param of 1000 for getting all entities for editing and etc.)
I investigated the history of the value 200 and there are no secrets behind this value. So it can just be increased.

MDEXP-440: Reference data is missing when there are more than 200 entities. 

---

descriptors/ModuleDescriptor-template.json
src/main/java/org/folio/clients/InventoryClient.java
src/main/java/org/folio/clients/SearchClient.java
src/main/java/org/folio/service/file/upload/FileUploadServiceImpl.java
src/main/java/org/folio/util/ExternalPathResolver.java
src/test/java/org/folio/rest/impl/InventoryClientTest.java
src/test/java/org/folio/rest/impl/MockServer.java
src/test/java/org/folio/rest/impl/SearchClientTest.java
src/test/java/org/folio/rest/impl/StorageTestSuite.java
src/test/java/org/folio/service/file/upload/FileUploadServiceUnitTest.java

[MDEXP-473](https://issues.folio.org/browse/MDEXP-473) - CQL export fails when effective location is included in the cql statement
The export fails when triggered by CQL and the effective location is a part of the statement. If works fine if the location is not present
* Introduced mod-search client to leverage `/search/instances/ids` API instead of mod-inventory storage API to get instance IDs …

MDEXP-473 - CQL export fails when effective location is included in the cql statement

---

src/main/java/org/folio/clients/SearchClient.java
src/test/java/org/folio/rest/impl/MockServer.java
src/test/java/org/folio/rest/impl/SearchClientTest.java

[MDEXP-475](https://issues.folio.org/browse/MDEXP-475) - Bugfest - the export cannot be triggered by the long CQL statement
The file with the long CQL statement never triggers the export
* Improved mod-data-export to support json streams …

MDEXP-475 - Bugfest - the export cannot be triggered by the long CQL statement

---

NEWS.md
pom.xml

[MDEXP-488](https://issues.folio.org/browse/MDEXP-488) - MDEXP (mod-data-export) Juniper Hotfix release

MDEXP-488 - Release 4.1.2

---

src/main/resources/rules/rulesDefault.json
src/test/resources/mapping/expected_marc.json
src/test/resources/mapping/given_inventory_instance.json

[MDEXP-124](https://issues.folio.org/browse/MDEXP-124) - Generate MARC bib record  - 500$a/notes
All note types associated with the inventory instance that are not marked as "staffOnly" should be mapped to 500 $a MARC field in accordance with the recommended mapping.
* Updated transformation rules
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid …

MDEXP-124 - Generate MARC bib record  - 500$a/notes

---

src/main/java/org/folio/clients/InventoryClient.java
src/main/java/org/folio/service/loader/RecordLoaderService.java
src/main/java/org/folio/service/loader/RecordLoaderServiceImpl.java
src/main/java/org/folio/service/manager/export/strategy/HoldingExportStrategyImpl.java
src/main/java/org/folio/service/mapping/converter/RecordConverter.java
src/test/java/org/folio/service/manager/export/HoldingExportStrategyUnitTest.java

Jira: https://issues.folio.org/browse/MDEXP-499
Add limit parameter to holdings request. Previously the limit param was omitted which caused only 10 holdings to be returned in a response.

MDEXP-499: Existing holdings UUIDs are reported as invalid while exporting holdings record

---

Jenkinsfile
README.md
ramls/samples/logs/errorLog.sample
ramls/samples/logs/errorLogCollection.sample
ramls/samples/logs/recordLog.sample

The doApiLint facility replaces runLintRamlCop
https://dev.folio.org/guides/api-lint/
The doApiDoc facility replaces publishAPI
https://dev.folio.org/guides/api-doc/
The https://dev.folio.org/reference/api/#mod-data-export section of API documentation will be automatically reconfigured:
https://dev.folio.org/reference/api/#explain-gather-config

MDEXP-511 FOLIO-3231 Use new api-lint and api-doc CI facilities

---

src/main/resources/templates/db_scripts/migration_scripts/add_default_profiles.sql

[MDEXP-542](https://issues.folio.org/browse/MDEXP-542) - Migration script fails if upgrading from version 4.2.4 to version 4.4.2
"Key (id) already exists" exception occurs upon migration script execution
* fixed migration script
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment.  Communication is paramount if that is to be achieved, …

MDEXP-542 - Migration script fails if upgrading from version 4.2.4 to version 4.4.2

---

descriptors/ModuleDescriptor-template.json

mod-inventory-storage has new major interface versions:
instance-storage 9.0
holdings-storage 6.0
item-storage 10.0
mod-data-export is not affected because the incompatible change is in the DELETE all APIs only that is not used by mod-data-export.
Only the okapiInterfaces need to be bumped in "requires" section of ModuleDescriptor-template.json

MDEXP-551: instance-storage 9.0, holdings-storage 6.0, item-storage 10.0

---

pom.xml
src/test/java/org/folio/service/export/storage/MinioExportStorageServiceTest.java

For Nolana upgrade all pom.xml dependencies to the latest supported version.
Upgrade minio from 8.3.0 to 8.4.5.
The minio upgrade indirectly upgrades com.squareup.okhttp3:okhttp from 4.8.1 to 4.10.0 fixing an Information Exposure vulnerability: https://security.snyk.io/vuln/SNYK-JAVA-COMSQUAREUPOKHTTP3-2958044
The minio upgrade indirectly upgrades kotlin-stdlib from 1.3.72 to 1.6.20 fixing Improper Locking https://nvd.nist.gov/vuln/detail/CVE-2022-24329 and Information Exposure https://nvd.nist.gov/vuln/detail/CVE-2020-29582
Upgrade log4j from 2.16.0 to 2.19.0 fixing Denial of Service (DoS) https://nvd.nist.gov/vuln/detail/CVE-2021-45105 and Arbitrary Code Execution https://nvd.nist.gov/vuln/detail/CVE-2021-44832
Upgrade com.jayway.jsonpath:json-path from 2.4.0 to 2.7.0 fixing Denial of …

MDEXP-564: Upgrade dependencies fixing vulnerabilities

---

src/main/java/org/folio/rest/impl/TenantReferenceAPI.java

[MDEXP-566](https://issues.folio.org/browse/MDEXP-566) - Reenabling module fails when reference data already exists
While reenabling mod-data-export-4.5.1 with loadReference=true flag during the upgrade to MorningGlory, it fails with 500 error when using an API call
* Fixed TenantReferenceAPI logic …

MDEXP-566 - Reenabling module fails when reference data already exists

---

.github/workflows/api-doc.yml
.github/workflows/api-lint.yml
.github/workflows/api-schema-lint.yml
Jenkinsfile
README.md
ramls/dataExport.raml

[FOLIO-3678](https://issues.folio.org/browse/FOLIO-3678)
Use GitHub Workflows for [api-lint](https://dev.folio.org/guides/api-lint/) and [api-schema-lint](https://dev.folio.org/guides/describe-schema/) and [api-doc](https://dev.folio.org/guides/api-doc/)
(instead of Jenkins-operated CI stages).

FOLIO-3678 MDEXP-608 Use GitHub Workflows api-lint and api-schema-lint and api-doc

---

src/main/resources/swagger.api/data-export.yaml
src/main/resources/swagger.api/schemas/error.json
src/main/resources/swagger.api/schemas/errors.json
src/main/resources/swagger.api/schemas/parameters.json

[MDEXP-623](https://issues.folio.org/browse/MDEXP-623) - Migrate RAML API definitions to OpenAPI definitions
In order to provide a back-compatible solution, the new back-end implementation should provide all existing APIs used by the UI or other services.
API definitions migrated to OpenAPI
Ideally all of the PRs involved in breaking changes would be …

MDEXP-623 - Migrate RAML API definitions to OpenAPI definitions

---

src/main/resources/rules/rulesDefault.json

[MDEXP-636](https://issues.folio.org/browse/MDEXP-636) - Add missing electronic access relationship values to default mapping rules
The electronic access relationship values should be added to default mapping rules:
"No information provided": " ",
"Related resource": "2",
"Component part(s) of resource": "3",
"Version of component part(s) of resource": "4",
"No display constant generated": "8"
Added values
- Are the JIRAs under …

MDEXP-636 - Add missing electronic access relationship values to default mapping rules

---

src/main/java/org/folio/service/manager/export/strategy/AbstractExportStrategy.java
src/main/java/org/folio/service/manager/export/strategy/AuthorityExportStrategyImpl.java
src/main/java/org/folio/service/manager/export/strategy/HoldingExportStrategyImpl.java
src/main/java/org/folio/service/manager/export/strategy/InstanceExportStrategyImpl.java

[MDEXP-625](https://issues.folio.org/browse/MDEXP-625) - Report affected instance when export contains negative number of failed records
Count only duplicate SRS records and change calculation logic for other failed.
Count number of not found records for failed.
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid …

MDEXP-625 - Report affected instance when export contains negative number of failed records

---

src/main/resources/templates/db_scripts/schema.json

[MDEXP-625](https://issues.folio.org/browse/MDEXP-625) - Fix migration scripts
Script update_failed.sql does not work after add_job_profile_names.sql.
Swap scripts.
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment.  Communication is paramount if that is to be achieved, …

MDEXP-625 Fix migration scripts

---

ramls/dataExport-job-profile.raml
src/main/java/org/folio/dao/JobProfileDao.java
src/main/java/org/folio/dao/impl/JobProfileDaoImpl.java
src/main/java/org/folio/rest/impl/DataExportImplJobProfileImpl.java
src/main/java/org/folio/service/profiles/jobprofile/JobProfileService.java
src/main/java/org/folio/service/profiles/jobprofile/JobProfileServiceImpl.java
src/test/java/org/folio/dao/profiles/JobProfileDaoUnitTest.java
src/test/java/org/folio/service/profiles/JobProfileServiceUnitTest.java

[MDEXP-109](https://issues.folio.org/browse/MDEXP-109) - Return list of the job profiles used in completed jobs
In the UI user will be able to filter completed export jobs by job profiles that were used in already completed jobs. In order to do so the UI will need to have a list of the job profiles to populate UI dropdown.
Select distinct job profiles from job executions.
- Do PRs exist …

MDEXP-109 - Return list of the job profiles used in completed jobs

---

src/main/java/org/folio/dao/JobExecutionDao.java
src/main/java/org/folio/dao/impl/JobExecutionDaoImpl.java
src/main/java/org/folio/service/file/upload/FileUploadServiceImpl.java
src/main/java/org/folio/service/job/JobExecutionServiceImpl.java
src/test/java/org/folio/service/job/JobExecutionServiceUnitTest.java

[MDEXP-668](https://issues.folio.org/browse/MDEXP-668) - Regression: Failed jobs listed always on top of the queue when completeDate is missing
In some cases when the job finishes with status Failed the completedDate is not populated.  This happens when the job fails due to connectivity issue  for example and the job stays on top of the queue, and the provided Ended Running date is always set to the current date even if the export occurred in the past.   Here is the example from the bugfest environment.
* Improved logic to set job execution completed date
* Updated logic to set completed date if it was not set to failed job executions upon expiring job execution API call
- Does …

MDEXP-668 - Regression: Failed jobs listed always on top of the queue when completeDate is missing

---

src/main/java/org/folio/dataexp/service/FileDefinitionsService.java
src/test/java/org/folio/dataexp/service/FileDefinitionsServiceTest.java

[MDEXP-743](https://folio-org.atlassian.net/browse/MDEXP-743) - Unhandled error when id is missing in POST /file-definition request's payload
In prior releases POST to https://folio-snapshot-okapi.dev.folio.org/data-export/file-definitions did not require an id in the payload, now a HTTP 500 error is returned if Id is not passed in.
* Fixed fileDefinitionService logic
- Are the JIRAs under active development? …

MDEXP-743 - Unhandled error when id is missing in POST /file-definition request's payload

---

.github/workflows/api-doc.yml
src/main/java/org/folio/dataexp/controllers/DataExportController.java
src/main/resources/swagger.api/data-export.yaml
src/test/java/org/folio/dataexp/controllers/DataExportControllerTest.java

[MDEXP-739](https://folio-org.atlassian.net/browse/MDEXP-739) - mod-data-export documentation updating
Documentation FOLIO Developers | Reference |  API documentation  still points to the ramls directory despite the fact mod-data-export was refactored to use spring-base and swagger. As a result API documentation is invalid. Also, in some cases there was a change in the contract and those changes will need to be documented in the Release notes so that the libraries that script their data export can adjust their scripts accordingly.
* Fixed settings and controller
If there are …

MDEXP-739 - mod-data-export documentation updating

---

.github/workflows/api-doc.yml
NEWS.md
pom.xml
src/main/java/org/folio/dataexp/controllers/DataExportController.java
src/main/java/org/folio/dataexp/controllers/MappingProfileController.java
src/main/java/org/folio/dataexp/exception/DataExportExceptionHandler.java
src/main/java/org/folio/dataexp/exception/mapping/profile/MappingProfileTransformationEmptyException.java
src/main/java/org/folio/dataexp/exception/mapping/profile/MappingProfileTransformationPatternException.java
src/main/java/org/folio/dataexp/service/FileDefinitionsService.java
src/main/java/org/folio/dataexp/service/MappingProfileService.java
src/main/resources/swagger.api/data-export.yaml
src/main/resources/swagger.api/schemas/profiles/transformations.json
src/test/java/org/folio/dataexp/controllers/DataExportControllerTest.java
src/test/java/org/folio/dataexp/controllers/MappingProfileControllerTest.java
src/test/java/org/folio/dataexp/service/FileDefinitionsServiceTest.java
src/test/java/org/folio/dataexp/service/MappingProfileServiceTest.java

Release 5.0.1

---

src/main/resources/db/changelog/changelog-master.xml
src/main/resources/db/changelog/changes/update_default_authority_profiles.sql
src/main/resources/db/changelog/changes/update_default_authority_profiles.xml

[MDEXP-753](https://folio-org.atlassian.net/browse/MDEXP-753) - Automate manual marking default authorities profiles as default
The “Required manual migration” instructions require sysops to manually search for the default authorities profile and to manually mark it as default.
Write migration script to set all default profiles to 'true'.
Ideally all of …

MDEXP-753 - Automate manual marking default authorities profiles as default

---

src/main/resources/db/changelog/changelog-master.xml
src/main/resources/db/changelog/changes/delete_error_logs_empty_job_execution_id.sql
src/main/resources/db/changelog/changes/delete_error_logs_empty_job_execution_id.xml
src/main/resources/db/changelog/changes/enrich_tables.sql

[MDEXP-752](https://folio-org.atlassian.net/browse/MDEXP-752) - Automate manual deletion of error_logs where `jsonb ->> 'jobExecutionId' = ''`
The “Required manual migration” instructions require sysops to manually delete records in error_logs where 'jobExecutionId' = ''. Those records must be deleted, otherwise enrich_tables.sql fails the migration when trying to convert the '' into UUID. This should be automated to reduce the number of manual tasks and to make the migration less error-prone.
Add the DELETE SQL statement to a new delete_error_logs_empty_job_execution_id.sql that runs before enrich_tables.sql.
- Does this introduce …

MDEXP-752: Automate manual deletion of error_logs where jobExecutionId=''

---

src/main/java/org/folio/dataexp/service/export/strategies/AbstractExportStrategy.java
src/main/java/org/folio/dataexp/service/export/strategies/JsonToMarcConverter.java
src/main/java/org/folio/dataexp/service/export/strategies/MarcSuppressProcessor.java
src/main/java/org/folio/dataexp/service/export/strategies/RuleFactory.java
src/test/java/org/folio/dataexp/service/export/strategies/AbstractExportStrategyTest.java
src/test/java/org/folio/dataexp/service/export/strategies/JsonToMarcConverterTest.java
src/test/java/org/folio/dataexp/service/export/strategies/MarcSuppressProcessorTest.java
src/test/java/org/folio/dataexp/service/export/strategies/RuleFactoryTest.java

[MDEXP-742](https://folio-org.atlassian.net/browse/MDEXP-742) - Exclude fields from export records
In some exports, libraries need to suppress MARC fields that might contain data relevant only for the libraries. 
* Added support of SRS records …

MDEXP-742 - Exclude fields from export records

---

src/main/java/org/folio/dataexp/service/export/strategies/AbstractExportStrategy.java
src/main/java/org/folio/dataexp/util/ErrorCode.java
src/test/java/org/folio/dataexp/service/export/strategies/AbstractExportStrategyTest.java

[MDEXP-748](https://folio-org.atlassian.net/browse/MDEXP-748)
Adding log entry for SRS records duplication in case externalId is absent in database.
Adding logging for handling error.
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment.  Communication is paramount if that is …

MDEXP-748 - Export all - Handle error details of bad data records 

---

src/main/java/org/folio/dataexp/repository/FolioInstanceAllRepository.java
src/main/java/org/folio/dataexp/service/export/strategies/InstancesExportAllStrategy.java
src/main/resources/db/changelog/changelog-master.xml
src/main/resources/db/changelog/changes/export_all_set_for_deletion.sql
src/main/resources/db/changelog/changes/export_all_set_for_deletion.xml

[MDEXP-793](https://folio-org.atlassian.net/browse/MDEXP-793) - Export all - Set LDR05 to "d" for records set for deletion
When a FOLIO instance is set for deletion and the exported MARC  is generated on the fly, LDR05 should be set to “d” during export all.  The export-all does not take into account FOLIO instances that are deleted through API call so the values stored in instance-audit table can be disregarded for  export-all purposes.
* Updated logic
- Do JIRAs exist to …

MDEXP-793 - Export all - Set LDR05 to "d" for records set for deletion

---

.github/workflows/api-doc.yml
.github/workflows/api-lint.yml
.github/workflows/api-schema-lint.yml

Bump actions/checkout from v3 (unsupported since August 2023) to supported v4.
(Note: api-doc.yml already has actions/checkout@v4).
Add workflow_dispatch, needed for https://folio-org.atlassian.net/browse/FOLIO-4183
This keeps the *.yml files in sync with the templates: https://github.com/folio-org/.github/tree/master/workflow-templates
Update .github/workflows/*.yml files.

Upgrade api workflows: actions/checkout@v4, workflow_dispatch
