folio-org/mod-data-export

PULL_REQUEST_TEMPLATE.md, src/main/resources/rules/rules.json
https://issues.folio.org/browse/MDEXP-6
- Mapped files using the file https://docs.google.com/spreadsheets/d/11lGBiPoetHuC3u-onVVLN4Mj5KtVHqJaQe4RqCxgGzo/edit#gid=1166940623
- Left a few more questions on the ticket to be mapped
##TODO
- Indicators handlings is yet to be decided
- There is also an case handling required in indicators, need to decide on a approach on that
Note: I also added PR template, it will be helpful if we add more details in each PR. Please try to fill the PR template whenever you are creating a PR
=> MDEXP-6 Create Inventory Instance to MARC Bib record mapping rules

descriptors/ModuleDescriptor-template.json, pom.xml, src/main/java/org/folio/clients/OkapiClients.java, src/main/java/org/folio/clients/OkapiClientsFactory.java, src/main/java/org/folio/clients/SynchronousOkapiClient.java, src/main/java/org/folio/clients/impl/SourceRecordStorageClient.java, src/main/java/org/folio/service/loader/BlockingRecordLoaderService.java, src/main/java/org/folio/service/loader/LoadResult.java, src/main/java/org/folio/service/loader/RecordLoaderService.java, src/main/java/org/folio/service/loader/SrsLoadResult.java, src/test/java/org/folio/rest/impl/HttpServerTestBase.java, src/test/java/org/folio/service/loader/BlockingRecordLoaderServiceTest.java, src/test/resources/log4j2-test.xml, src/test/resources/marcs_db.json
For a batch of UUID retrieve MARC records by calling SRS
Synchronous implementation of RecordLoaderService that accepts list of uuids and returns the corresponding marc records if they exist in SRS.
=> MDEXP-36: RecordLoaderService: retrieve MARC records from SRS

FileUploadApi.md
To have documentation for the file upload API.
Documentation is created in Github repo of the mod-data-export
Available upload REST API is described
Structure of request/response is described
curl examples exist
=> MDEXP-53 Create documentation for the file upload API

ramls/dataExport.raml, ramls/samples/exportedFile.sample, ramls/samples/jobExecution.sample, ramls/samples/jobProfile.sample, ramls/schemas/exportedFile.json, ramls/schemas/jobExecution.json, ramls/schemas/jobProfile.json, src/main/resources/templates/db_scripts/schema.json
Add new entity for jobExecution managment.
=> MDEXP-61: Create JobExecution entity

FileUploadApi.md
=> MDEXP-53 Corrected introduction in the file upload API documentation

src/main/java/org/folio/service/manager/inputdatamanager/InputDataManagerImpl.java
=> MDEXP-58 Fix export batch size to 50

README.md
Update the documentation to include information about S3.
=> MDEXP-68: Update the documentation to include information about S3

ramls/samples/jobExecution.sample, ramls/samples/jobExecutionCollection.sample, ramls/schemas/jobExecution.json, src/main/java/org/folio/dao/FileDefinitionDao.java, src/main/java/org/folio/dao/JobExecutionDao.java, src/main/java/org/folio/dao/impl/FileDefinitionDaoImpl.java, src/main/java/org/folio/dao/impl/JobExecutionDaoImpl.java, src/main/java/org/folio/service/job/JobExecutionService.java, src/main/java/org/folio/service/job/JobExecutionServiceImpl.java, src/main/java/org/folio/service/manager/inputdatamanager/InputDataManagerImpl.java, src/main/java/org/folio/service/manager/inputdatamanager/reader/LocalStorageCsvSourceReader.java, src/test/java/org/folio/service/manager/inputdatamanager/InputDataManagerTest.java
Update status of job execution in database in pair with file definition export process.
=> MDEXP-69: Update a jobExecution entry in DB

src/main/java/org/folio/service/manager/input/InputDataManagerImpl.java, src/test/java/org/folio/rest/impl/EndToEndTest.java
Fix naming in user info
While it's helpful for reviewers to help identify potential problems, ensuring that it's safe to merge is ultimately the …
=> MDEXP-81 fix stable master build

src/main/java/org/folio/dao/impl/JobExecutionDaoImpl.java, src/main/java/org/folio/rest/exceptions/ServiceException.java, src/main/java/org/folio/rest/impl/ModTenantAPI.java, src/main/java/org/folio/service/manager/export/ExportManagerImpl.java, src/main/java/org/folio/service/manager/input/InputDataManagerImpl.java
=> MDEXP-76 Fix empty error message

src/main/java/org/folio/service/manager/export/ExportManagerImpl.java, src/test/java/org/folio/service/manager/export/ExportManagerUnitTest.java
Added logging to track records that are not presenting in SRS
=> Mdexp 91 improve logging

src/main/resources/templates/db_scripts/schema.json
This was observed in bugfest. Logs were having a lot of noise like below:
https://issues.folio.org/browse/MDEXP-95
- A FT index is needed and not just index
- Removing the earlier index and adding a FT index …
=> MDEXP-95- Add FT index

src/main/java/org/folio/service/manager/input/InputDataManagerImpl.java
We need to fix the current clean up behavior to remove generated files as well as csv files.
Take metadata object from the ExportRequest and put it to exportFileDefinition, to let CleanupService to recognize it …
=> MDEXP-94 bugfix

NEWS.md, pom.xml, src/main/resources/templates/db_scripts/schema.json
https://issues.folio.org/browse/MDEXP-83 - Release v1.1.0 with features and bugfixes needed for Q1-2020
- Following guidelines from 
https://dev.folio.org/guidelines/release-procedures/#maven-based-modules
https://wiki.folio.org/display/FOLIJET/Acquisitions+-+Release+Procedures
=> MDEXP-83: Release- 1.1.0

NEWS.md, pom.xml, src/main/resources/templates/db_scripts/job_execution_sequence.sql, src/main/resources/templates/db_scripts/schema.json
https://issues.folio.org/browse/MDEXP-119
FromModuleVersion was not updated, causing the upgrades to not pickup the new Sequence introduced
- update fromModule version to latest release
- set the sequence start to 1 instead of 0
=> MDEXP-119: Release 1.1.1

descriptors/ModuleDescriptor-template.json, src/main/java/org/folio/clients/StorageClient.java, src/main/java/org/folio/service/loader/RecordLoaderService.java, src/main/java/org/folio/service/loader/RecordLoaderServiceImpl.java, src/main/java/org/folio/service/manager/export/ExportManagerImpl.java, src/test/java/org/folio/rest/impl/EndToEndTest.java, src/test/java/org/folio/service/loader/RecordLoaderServiceUnitTest.java, src/test/java/org/folio/service/manager/export/ExportManagerUnitTest.java, src/test/resources/InventoryStorageEmptyResponse.json, src/test/resources/inventoryStorageResponse.json
https://issues.folio.org/browse/MDEXP-37
Provide availability to get records from inventory, if they are not present in SRS.
While it's helpful for …
=> MDEXP-37 Provide client for retrieving inventory instance records

src/test/resources/mockData/test_instance_to_post.json, src/test/resources/mockData/test_instance_type_to_post.json
https://issues.folio.org/browse/MDEXP-135
Test data for creating an instance for API tests. …
=> MDEXP-135 Test data for creating instance

ramls/samples/profiles/mappingProfile.sample, ramls/samples/profiles/mappingProfileCollection.sample, ramls/samples/profiles/transformations.sample, ramls/schemas/profiles/mappingProfile.json, ramls/schemas/profiles/transformations.json, src/test/resources/profiles/mappingProfile.json
Change type of a field transformations.enabled to boolean …
=> MDEXP-162 change trasnfromations.enabled to boolean type

src/main/java/org/folio/service/mapping/processor/translations/TranslationsHolder.java, src/test/java/org/folio/service/mapping/TranslationFunctionUnitTest.java
https://issues.folio.org/browse/MDEXP-189
Added checks for fields that are filled in the field '008'.
While it's helpful for reviewers to help …
=> MDEXP-189 Fix NPE for 008 field

src/main/resources/templates/db_scripts/schema.json
Mapping profile and job profile must have unique name in order to easily identify the records 
add unique index on both tables
- change fromModuleVersion if necessary, after mod-srs is released …
=> adding unique index to MP, JP

descriptors/ModuleDescriptor-template.json, src/main/java/org/folio/clients/ClientUtil.java, src/main/java/org/folio/clients/SourceRecordStorageClient.java, src/main/java/org/folio/service/loader/RecordLoaderService.java, src/main/java/org/folio/service/loader/RecordLoaderServiceImpl.java, src/main/java/org/folio/service/manager/export/ExportManagerImpl.java, src/main/java/org/folio/service/mapping/convertor/SrsRecordConvertorService.java, src/main/java/org/folio/util/ExternalPathResolver.java, src/test/java/org/folio/clients/SourceRecordStorageUnitTest.java, src/test/java/org/folio/rest/MockServer.java, src/test/java/org/folio/rest/impl/DataExportTest.java, src/test/java/org/folio/rest/impl/EndToEndTest.java, src/test/java/org/folio/service/export/ExportServiceUnitTest.java, src/test/java/org/folio/service/loader/RecordLoaderServiceUnitTest.java, src/test/java/org/folio/service/manager/export/ExportManagerUnitTest.java, src/test/java/org/folio/service/mapping/convertor/SrsRecordConvertorServiceUnitTest.java, src/test/resources/mockData/srs/get_records_response.json
https://issues.folio.org/browse/MDEXP-199
- Refactor to use updated API (prepare the PR to be merged the same day as SRS refactoring-master is merged to master)
- Verify the functionality is working on the environment
- Notify Folijet team that SRS can be released
1. The SRS leaves using CQL in favour of SQL, so the API is changed
2. Interface source-storage-records 1.0 is updated to source-storage-source-records 2.0, permission is updated too
3. API is updated, no need to retrieve a collection of records using GET request, now SRS provides POST API to retrieve records sending UUIDs in the request body
4. Updated unit tests
If there are breaking changes, …
=> MDEXP-199 Updates to the factored version of SRS

NEWS.md, pom.xml, src/main/resources/templates/db_scripts/schema.json
https://issues.folio.org/browse/MDEXP-206
Release to update to latest mod-SRS dependency
- Update NEWS.md
- also updated the fromModule version in schema.json to latest version 2.1.0
=> MDEXP-206: Release 2.1.0

src/main/java/org/folio/service/job/JobExecutionServiceImpl.java, src/test/java/org/folio/service/job/JobExecutionServiceUnitTest.java
https://issues.folio.org/browse/MDEXP-208
-  Fix issue when jobProfileName field not always populating while getting job execution;
- Get associated Job profile by ids query, instead of getting all job profiles from the DB;
- Unit tests are updated
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment.  Communication is paramount if that …
=> MDEXP-208 Fix issue when jobProfileName field not always populating while getting job execution

src/main/java/org/folio/service/job/JobExecutionServiceImpl.java
Refactor some code in JobExecutionService class and added a check to avoid unnecessarily call …
=> MDEXP-208-2 Add check to avoid unnecessary call to get Jobprofile

src/main/java/org/folio/service/job/JobExecutionServiceImpl.java, src/test/java/org/folio/service/job/JobExecutionServiceUnitTest.java
Currently, if there are no job executions in the DB, then there are errors in the logs, cause we are trying to get job profile for an empty job execution collection. Added necessary check to avoid this error …
=> MDEXP-208 Added necessary check to clear the logs

NEWS.md, pom.xml
https://issues.folio.org/browse/MDEXP-209- bugfix release for Q22020- Golden rod
- Just add news as no versions are required to be changed
=> MDEXP-209 - Release 2.1.1

src/main/java/org/folio/service/mapping/MappingServiceImpl.java
https://issues.folio.org/browse/MDEXP-220
- As we determined the cause of issue to be because of using multiple threads, setting the number of threads back to 1 until more investigation is done and issue is fixed …
=> MDEXP-220: Handling inconsistent export results

src/main/java/org/folio/service/mapping/MappingServiceImpl.java
Using synchronized list to fix a bug with concurrency
While it's helpful for reviewers to help identify potential problems, ensuring that it's safe to …
=> MDEXP-166 Make records processing parallel, fixed concurrency issue

src/main/java/org/folio/service/transformationfields/TransformationConfigConstants.java, src/main/java/org/folio/service/transformationfields/TransformationFieldsConfig.java, src/main/java/org/folio/service/transformationfields/TransformationFieldsServiceImpl.java, src/test/java/org/folio/rest/impl/TransformationFieldsServiceTest.java, src/test/java/org/folio/service/transformationfields/TransformationFieldsServiceUnitTest.java, src/test/resources/mapping/expectedTransformationFields.json
https://issues.folio.org/browse/MDEXP-210
https://issues.folio.org/browse/MDEXP-218
Display transformation fields for Instances and Items. 
This PR deals with just simple fields
- Added the simple fields to the enum set
- Added a comparator for sort
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment.  Communication is paramount if that …
=> MDEXP-210 and MDEXP-218- Simple fields for Instance and Item

src/main/java/org/folio/service/mapping/RuleFactory.java, src/test/java/org/folio/service/mapping/MappingServiceUnitTest.java
https://issues.folio.org/browse/MDEXP-233
Implement logic of custom sorting for DataSource subfields in alphabetical order and apply it to rules generated by mapping profile transformations.
Implement custom Comparator with the logic of sorting by DataSource type. …
=> MDEXP-233 Apply sorting for subfields

descriptors/ModuleDescriptor-template.json, src/main/java/org/folio/clients/InventoryClient.java, src/main/java/org/folio/service/mapping/RuleFactory.java, src/main/java/org/folio/service/mapping/referencedata/ReferenceDataProvider.java, src/main/java/org/folio/util/ExternalPathResolver.java, src/test/java/org/folio/rest/impl/InventoryClientTest.java, src/test/java/org/folio/rest/impl/MockServer.java, src/test/resources/mockData/inventory/get_call_number_types_response.json
https://issues.folio.org/browse/MDEXP-249
**APPROACH**
- Add translation function for effective call number type;
- Add call to inventory for retrieving call-number-types;
**NOTES**
This PR should be merged after https://github.com/folio-org/generate-marc-utils/pull/8 the same day.
=> MDEXP-249 Applying mapping profile- item-effective call number

descriptors/ModuleDescriptor-template.json, src/main/java/org/folio/clients/InventoryClient.java, src/main/java/org/folio/service/mapping/RuleFactory.java, src/main/java/org/folio/service/mapping/referencedata/ReferenceDataImpl.java, src/main/java/org/folio/service/mapping/referencedata/ReferenceDataProvider.java, src/main/java/org/folio/service/mapping/translationbuilder/DefaultTranslationBuilder.java, src/main/java/org/folio/service/mapping/translationbuilder/LocationTranslationBuilder.java, src/main/java/org/folio/service/mapping/translationbuilder/TranslationBuilder.java, src/main/java/org/folio/util/ExternalPathResolver.java, src/test/java/org/folio/TestUtil.java, src/test/java/org/folio/rest/impl/DataExportTest.java, src/test/java/org/folio/rest/impl/InventoryClientTest.java, src/test/java/org/folio/rest/impl/MockServer.java, src/test/java/org/folio/service/mapping/MappingServiceUnitTest.java, src/test/java/org/folio/service/mapping/RuleFactoryUnitTest.java, src/test/java/org/folio/service/mapping/convertor/SrsRecordConvertorServiceUnitTest.java, src/test/java/org/folio/util/ReferenceDataResponseUtil.java, src/test/resources/mapping/expected_marc_record_with_only_holdings_and_items.json, src/test/resources/mapping/expected_marc_record_with_only_holdings_and_items_and_instances.json, src/test/resources/mapping/given_HoldingsItems.json, src/test/resources/mapping/given_inventory_instance.json, src/test/resources/mockData/inventory/get_campuses_response.json, src/test/resources/mockData/inventory/get_institutions_response.json, src/test/resources/mockData/inventory/get_libraries_response.json, src/test/resources/mockData/inventory/get_locations_response.json
Add a mechanism for applying location related fields like libraries, campuses, and institutions. Create a new abstraction TranslationBuilder to handle the creation of specific translation functions with necessary parameters. Remove usage of the old location translations.
=> MDEXP-252 Applying mapping profile - location fields - holdings and item

src/main/java/org/folio/service/mapping/RuleFactory.java, src/test/java/org/folio/TestUtil.java, src/test/java/org/folio/service/mapping/RuleFactoryUnitTest.java
Quick fix of index out of bound exception in RuleFactory
=> MDEXP-252 Fix index out of bound

Dockerfile, Jenkinsfile, pom.xml
https://issues.folio.org/browse/MDEXP-211
- Upgrade to use Java 11
- Upgrade to use RMB 31.0.2
Followed https://github.com/folio-org/raml-module-builder/blob/master/doc/upgrading.md#version-310 …
=> MDEXP-211 - Upgrade to java 11

.rancher-pipeline.yml
This is to be done as part of the java 11 upgrade to the module
- change the yml file to use the latest jdk
While it's helpful for reviewers to help …
=> Java11 rancher upgrade

.rancher-pipeline.yml
Fix issue when no updates after building module by pipeline on rancher
=> Concorde pipeline buildid

descriptors/ModuleDescriptor-template.json, ramls/dataExport-logs.raml, ramls/samples/logs/errorLog.sample, ramls/samples/logs/errorLogCollection.sample, ramls/samples/logs/recordLog.sample, ramls/schemas/logs/errorLog.json, ramls/schemas/logs/errorLogCollection.json, ramls/schemas/logs/recordLog.json, src/main/java/org/folio/dao/ErrorLogDao.java, src/main/java/org/folio/dao/impl/ErrorLogDaoImpl.java, src/main/java/org/folio/rest/impl/DataExportImplErrorLogsImpl.java, src/main/java/org/folio/rest/impl/DataExportImplLogsImpl.java, src/main/java/org/folio/service/logs/ErrorLogService.java, src/main/java/org/folio/service/logs/ErrorLogServiceImpl.java, src/main/java/org/folio/service/mapping/RuleFactory.java, src/main/java/org/folio/service/mapping/rulebuilder/DefaultRuleBuilder.java, src/main/java/org/folio/util/HelperUtils.java, src/main/resources/templates/db_scripts/schema.json, src/test/java/org/folio/dao/profiles/ErrorLogDaoImplUnitTest.java, src/test/java/org/folio/rest/impl/ErrorLogsTest.java, src/test/java/org/folio/rest/impl/RestVerticleTestBase.java, src/test/java/org/folio/service/logs/ErrorLogServiceUnitTest.java
MDEXP-261 Create API for error log handling
While it's helpful for reviewers to help identify potential problems, ensuring that it's safe to merge is …
=> MDEXP-261 Create API for error log handling

src/main/java/org/folio/service/export/storage/AWSStorageServiceImpl.java, src/test/java/org/folio/service/export/storage/ExportStorageServiceUnitTest.java
https://issues.folio.org/browse/MDEXP-300
Added shutDown of AWS client in getFileDownloadLink() method in finally block.
=> MDEXP-300 Close AWS client after dolwnloading a link

src/main/java/org/folio/service/export/ExportService.java, src/main/java/org/folio/service/export/LocalFileSystemExportService.java, src/main/java/org/folio/service/export/storage/AWSStorageServiceImpl.java, src/main/java/org/folio/service/file/reader/LocalStorageCsvSourceReader.java, src/main/java/org/folio/service/file/storage/LocalFileSystemStorage.java, src/main/java/org/folio/service/logs/ErrorLogService.java, src/main/java/org/folio/service/logs/ErrorLogServiceImpl.java, src/main/java/org/folio/service/manager/export/ExportManagerImpl.java, src/main/java/org/folio/service/manager/input/InputDataManagerImpl.java, src/main/java/org/folio/service/mapping/MappingServiceImpl.java, src/test/java/org/folio/service/export/ExportServiceUnitTest.java, src/test/java/org/folio/service/export/storage/ExportStorageServiceUnitTest.java, src/test/java/org/folio/service/logs/ErrorLogServiceUnitTest.java, src/test/java/org/folio/service/manager/input/InputDataManagerUnitTest.java, src/test/java/org/folio/service/mapping/MappingServiceUnitTest.java
While it's helpful for reviewers to help identify potential problems, ensuring that it's safe to merge is ultimately the responsibility of the PR …
=> MDEXP-257 Log errors for inventory Instance record exports

src/main/java/org/folio/clients/InventoryClient.java, src/test/resources/mockData/test_file_to_upload.cql
Remove brackets before and after query param for /instance-bulks/ids request to apply cql query correctly
Add test cql file for API tests
=> Fix request to /instance-bulk/ids to get ids by query

NEWS.md, descriptors/ModuleDescriptor-template.json, pom.xml
https://issues.folio.org/browse/MDEXP-289
- Major release for HoneySuckle
- added Readme
- updated version for generate-marc-utils 
- updated the minor versions for all the dependent interfaces
=> MDEXP-289 - Release 3.0.0

src/main/java/org/folio/service/file/reader/LocalStorageCsvSourceReader.java, src/test/resources/files/InventoryUUIDsWithInvalidUUIDs.csv
https://issues.folio.org/browse/MDEXP-176
Change regex in source reader to avoid any special characters, except -
=> MDEXP-176 Add regex with excepting special characters

pom.xml
https://issues.folio.org/browse/MDEXP-307
We are not dependant on guava library at all
- Remove the guava dependency
- Update to use latest generate-marc-utils …
=> MDEXP-307: update guava to fix security issue

src/main/java/org/folio/service/manager/export/ExportManagerImpl.java
https://issues.folio.org/browse/MDEXP-313
populate number of not found records in error log when 0 records exported in last batch
=> MDEXP-313 Fix number of not found 0 records exported in last batch

pom.xml, src/main/java/org/folio/service/logs/ErrorLogServiceImpl.java, src/test/java/org/folio/service/logs/ErrorLogServiceUnitTest.java
https://issues.folio.org/browse/MDEXP-316
Since the structure of the JsonObject that goes into the mapping process has changed, we have to change the creation of AffectedRecords, so we added changes to this PR.
=> MDEXP-316 Fix error logs doesn`t contain item info

src/main/java/org/folio/service/manager/export/ExportManagerImpl.java, src/main/resources/templates/db_scripts/migration_scripts/remove_hasSameTagInHoldings.sql, src/main/resources/templates/db_scripts/migration_scripts/update_transformations_mapping_profile.sql, src/main/resources/templates/db_scripts/schema.json
https://issues.folio.org/browse/MDEXP-314
Created a migration script to update fieldId in mapping profile.
Also created a script to update path field for ITEM record type, as we changed it, it is should contain 'holdings[*]'.
Also changed the script to remove hasSameTagInHoldings, as it doesn't work correctly.
=> MDEXP-314 Mapping profile migrate fieldIds

NEWS.md, src/main/resources/templates/db_scripts/migration_scripts/update_transformations_mapping_profile.sql, src/main/resources/templates/db_scripts/schema.json
https://issues.folio.org/browse/MDEXP-333
This PR created to merge only changes that need for v3.0.2 release
=> MDEXP-233 v3.0.2 release changes

src/main/java/org/folio/service/logs/ErrorLogService.java, src/main/java/org/folio/service/manager/export/ExportManagerImpl.java, src/main/java/org/folio/service/manager/input/InputDataManagerImpl.java, src/main/java/org/folio/service/transformationfields/TransformationFieldsConfig.java, src/test/java/org/folio/rest/impl/StorageCleanupServiceImplTest.java
There were test failures as below:
`
[ERROR]   StorageTestSuite$DataExportTestNested.testExportByCQL_GenerateRecordsOnFly_andUnderlyingSrs org.opentest4j.AssertionFailedError: expected: <COMPLETED> but was: <COMPLETED_WITH_ERRORS>
[ERROR]   StorageTestSuite$DataExportTestNested.testExportByCSV_GenerateRecordsOnFly org.opentest4j.AssertionFailedError: expected: <COMPLETED> but was: <COMPLETED_WITH_ERRORS>
[ERROR]   StorageTestSuite$DataExportTestNested.testExportByCSV_UnderlyingSrsOnly_COMPLETED_job org.opentest4j.AssertionFailedError: expected: <COMPLETED> but was: <COMPLETED_WITH_ERRORS>
[ERROR]   StorageTestSuite$DataExportTestNested.testExportByCSV_UnderlyingSrsWithProfileTransformationsNoCallToSRS org.opentest4j.AssertionFailedError: expected: <COMPLETED> but was: …
=> MDEXP-337: Fixing bizzare unit tests

NEWS.md, README.md
PR with only required changes to be merged to master from https://github.com/folio-org/mod-data-export/pull/206
The cherry picked branch has a lot of changes that need not go to master
Add only release news for 3.0.3, everything else must be present in master
=> MDEXP336: Release 3.0.3 merge changes

NEWS.md
PR with only required changes to be merged to master from #209 
Purpose
The cherry-picked branch has a lot of changes that need not go to master
Approach
Add only release news for 3.0.4, everything else must be present in the master
=> Release 3.0.4 changes in news

ramls/schemas/profiles/transformations.json, src/test/java/org/folio/rest/impl/MappingProfileServiceTest.java, src/test/resources/endToEndTestFiles/mappingProfile.json, src/test/resources/profiles/mappingProfile.json
Add validation to the transformation elements.
Add regexp to json file
Jira: https://issues.folio.org/browse/MDEXP-315
While it's helpful for …
=> MDEXP-315: Add validation to the transformation elements

src/main/java/org/folio/service/mapping/MappingServiceImpl.java, src/main/java/org/folio/service/mapping/referencedata/ReferenceDataImpl.java, src/main/java/org/folio/service/mapping/referencedata/ReferenceDataProvider.java, src/main/java/org/folio/service/transformationfields/TransformationFieldsServiceImpl.java, src/test/java/org/folio/service/mapping/MappingServiceUnitTest.java, src/test/java/org/folio/service/mapping/converter/SrsRecordConverterServiceUnitTest.java, src/test/java/org/folio/service/transformationfields/TransformationFieldsServiceUnitTest.java
While it's helpful for reviewers to help identify potential problems, ensuring that it's safe to merge is ultimately the responsibility of the PR …
=> MDEXP-302/GMU-1 Detect which record exactly leads to the exception

src/main/resources/rules/rulesDefault.json, src/test/resources/mapping/expectedTransformationFields.json, src/test/resources/mockData/inventory/get_identifier_types_response.json
https://issues.folio.org/browse/MDEXP-182
Using 'Cancelled system control number' instead of 'Cancelled system control numbers'
While it's helpful for …
=> MDEX-182 Using singular form instead of plural

.rancher-pipeline.yml
https://issues.folio.org/browse/MDEXP-340
Catalog template changed after full rancher redeploy, change the config file.
=> MDEXP-340 Update rancher configs

descriptors/ModuleDescriptor-template.json
https://issues.folio.org/browse/MDEXP-360
Returned tenant api to the module descriptor
=> MDEXP-360 Fix wrong update to rmb 32

src/main/java/org/folio/service/export/storage/AWSStorageServiceImpl.java, src/main/java/org/folio/service/export/storage/ExportStorageService.java, src/main/java/org/folio/service/job/JobExecutionServiceImpl.java, src/test/java/org/folio/rest/impl/ErrorLogsTest.java, src/test/java/org/folio/rest/impl/JobExecutionServiceTest.java, src/test/java/org/folio/service/export/storage/ExportStorageServiceUnitTest.java, src/test/java/org/folio/service/job/JobExecutionServiceUnitTest.java
https://issues.folio.org/browse/MDEXP-310
Add check if job execution is in progress, then we will not remove it. 
Also added deleting file from S3 when deleting job execution. …
=> MDEXP-310 Remove files from S3 while delete job execution

PERSONAL_DATA_DISCLOSURE.md
https://issues.folio.org/browse/MDEXP-358
Checked what personal info data-export storing. We are using user`s: firstName., lastName and userName in mapping/job profiles.
=> MDEXP-358 Add personal data disclosure form

src/main/java/org/folio/service/logs/ErrorLogService.java, src/main/java/org/folio/service/logs/ErrorLogServiceImpl.java, src/main/java/org/folio/service/mapping/MappingServiceImpl.java, src/main/java/org/folio/util/ErrorCode.java, src/test/java/org/folio/service/logs/ErrorLogServiceUnitTest.java, src/test/java/org/folio/service/mapping/MappingServiceUnitTest.java
https://issues.folio.org/browse/MDEXP-367
To change error message for affected record, add fieldsData: fieldName and fieldValue
Change errorMessage for affected records, add fieldData, update test
This PR will be green after this one https://github.com/folio-org/generate-marc-utils/pull/42 will be merged …
=> MDEXP-367 Change errorLog message: added fieldsData

pom.xml
https://issues.folio.org/browse/MDEXP-372
Update to latest rmb and check if everything is ok.
Updated to latest RMB, deployed module to local vagrant, checked that everything working fine.
=> MDEXP-372 Update to rmb 32.2.0

src/main/java/org/folio/service/mapping/rulebuilder/TransformationRuleBuilder.java, src/test/java/org/folio/service/mapping/MappingServiceUnitTest.java, src/test/resources/mapping/expected_marc_record_with_only_holdings_and_items.json, src/test/resources/mapping/expected_marc_record_with_only_holdings_and_items_and_instances.json
https://issues.folio.org/browse/MDEXP-385
Fix issue when subfield 3 not always present in MARC file. …
=> MDEXP-385 Fix issue when subfield 3 not always present

pom.xml
While it's helpful for reviewers to help identify potential problems, ensuring that it's safe to merge is ultimately the responsibility of the PR …
=> MDEXP-388::0% coverage reported by Sonarcloud for mod-data-export

descriptors/ModuleDescriptor-template.json
https://issues.folio.org/browse/MDEXP-407
Increase version of the “source-storage-source-records” from "2.0" to "3.0"
While it's helpful for reviewers …
=> MDEXP-407 Update interface version

NEWS.md, pom.xml
Jira: https://issues.folio.org/browse/MDEXP-384
Release mod-data-export 4.1.0
=> MDEXP-384: release mod-data-export 4.1.0

pom.xml, src/test/java/org/folio/rest/impl/RestVerticleTestBase.java, src/test/java/org/folio/rest/impl/StorageTestSuite.java
[MDEXP-395](https://issues.folio.org/browse/MDEXP-395) - data-export- Upgrade to RMB 33
We need to upgrade to latest RMB modules. 
- follow  https://github.com/folio-org/raml-module-builder/blob/master/doc/upgrading.md#version-330
- update code
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment.  Communication is paramount if that is …
=> MDEXP-395 - data-export- Upgrade to RMB 33

pom.xml
While it's helpful for reviewers to help identify potential problems, ensuring that it's safe to merge is ultimately the responsibility of the PR …
=> Increase artefact version

src/main/java/org/folio/clients/ClientUtil.java, src/main/java/org/folio/clients/SourceRecordStorageClient.java, src/main/java/org/folio/dao/impl/ErrorLogDaoImpl.java, src/main/java/org/folio/dao/impl/JobExecutionDaoImpl.java, src/main/java/org/folio/dao/impl/JobProfileDaoImpl.java, src/main/java/org/folio/dao/impl/MappingProfileDaoImpl.java, src/main/java/org/folio/rest/impl/DataExportImpl.java, src/main/java/org/folio/service/export/storage/AWSStorageServiceImpl.java, src/main/java/org/folio/service/manager/input/InputDataManagerImpl.java, src/main/resources/log4j2.properties
[MDEXP-441](https://issues.folio.org/browse/MDEXP-441) - Memory utilisation issues
Decrease memory consumption of logger.
Enable INFO level for logger, move to DEBUG "hard" operations (with large responses). …
=> MDEXP-441 - Memory utilisation issues (logging optimisation)

NEWS.md, pom.xml, src/main/java/org/folio/clients/SearchClient.java, src/main/java/org/folio/rest/impl/DataExportImplFileDefinitionImpl.java, src/test/java/org/folio/rest/impl/InventorySearchClientTest.java, src/test/java/org/folio/rest/impl/MockServer.java
[MDEXP-476](https://issues.folio.org/browse/MDEXP-476) - Release 4.2.3
=> MDEXP-476 - Release 4.2.3

README.md
[MDEXP-470](https://issues.folio.org/browse/MDEXP-470) - Export fails after /data-export/expire-jobs endpoint invocation
Update README.md due to the changes in the system requirements.
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment.  Communication is paramount if that is to be achieved, especially as the number of intermodule and …
=> MDEXP-470 - Export fails after /data-export/expire-jobs endpoint invocation

pom.xml
[MDEXP-484](https://issues.folio.org/browse/MDEXP-484) - Kiwi R3 2021 - Log4j vulnerability verification and correction
=> MDEXP-484 - Kiwi R3 2021 - Log4j vulnerability verification and correction

NEWS.md, pom.xml
[MDEXP-489](https://issues.folio.org/browse/MDEXP-489) - MDEXP (mod-data-export) Kiwi Bugfix release
=> MDEXP-489 - Release 4.2.4

src/main/java/org/folio/service/mapping/handler/RuleHandler.java
Jira: https://issues.folio.org/browse/GMU-24
Update the code with the latest GMU library changes
=> GMU-24: adjust the code to the newly introduced library changes.

NEWS.md, pom.xml
Jira:
Relase mod-data-export v4.3.0
=> Release mod-data-export v4.3.0

ramls/schemas/profiles/jobProfile.json, ramls/schemas/profiles/mappingProfile.json, src/main/resources/data/job-profiles/default_holdings_job_profile.json, src/main/resources/data/job-profiles/default_instance_job_profile.json, src/main/resources/data/mapping-profiles/default_holdings_mapping_profile.json, src/main/resources/data/mapping-profiles/default_instance_mapping_profile.json, src/main/resources/templates/db_scripts/migration_scripts/update_job_profile_default_value.sql, src/main/resources/templates/db_scripts/migration_scripts/update_mapping_profile_default_value.sql, src/main/resources/templates/db_scripts/schema.json
[MDEXP-213](https://issues.folio.org/browse/MDEXP-213) - Implement a way to identify default profiles (instances and holdings)
Additional field default with Boolean value to identify default profile …
=> MDEXP-213 - Implement a way to identify default profiles (instances and holdings)

NEWS.md, pom.xml
Update README and pom.xml in master-branch
=> MDEXP-506 - Release-4.4.0

src/main/java/org/folio/rest/impl/DataExportImpl.java, src/test/java/org/folio/rest/impl/DataExportTest.java
Support quickExport for Authorities IDs
=> MDEXP-513 Support quickExport for Authorities IDs

NEWS.md, pom.xml
[MDEXP-502](https://issues.folio.org/browse/MDEXP-502)  - MDEXP (mod-data-export) release
While it's helpful for reviewers to help identify potential …
=> MDEXP-502 -  Release v.4.5.0

src/main/resources/templates/db_scripts/schema.json
[MDEXP-543](https://issues.folio.org/browse/MDEXP-543) - Migration fails - MG
Migration scripts for version 4.5.0 cannot be applied due to snippet version 4.4.0.
Increase snippet version to 4.5.1 …
=> MDEXP-543 - Migration fails - MG

NEWS.md, pom.xml
[MDEXP-544](https://issues.folio.org/browse/MDEXP-544) - Release 4.5.1
=> MDEXP-544 - Release 4.5.1

NEWS.md, pom.xml
[MDEXP-548](https://issues.folio.org/browse/MDEXP-548) - MDEXP (mod-data-export) Lotus HF#3 release
=> MDEXP-548 - Release 4.4.3

pom.xml
[MDEXP-554](https://issues.folio.org/browse/MDEXP-554) - Use SNAPSHOT version of generate-marc-utils
Use SNAPSHOT version of generate-marc-utils library for mod-data-export module to verify changes in [GMU-33](https://issues.folio.org/browse/GMU-33)
Change pom.xml. …
=> MDEXP-554 - Use SNAPSHOT version of generate-marc-utils

pom.xml
[MDEXP-558](https://issues.folio.org/browse/MDEXP-558) - mod-data-export: Upgrade RAML Module Builder
- Are the JIRAs under active development? …
=> MDEXP-558 - mod-data-export: Upgrade RAML Module Builder

pom.xml
[MDEXP-561](https://issues.folio.org/browse/MDEXP-561) - Replace generate-marc-utils -SNAPSHOT by release
While it's helpful for reviewers to help …
=> MDEXP-561 - Replace generate-marc-utils -SNAPSHOT by release

NEWS.md, pom.xml
[MDEXP-536](https://issues.folio.org/browse/MDEXP-536) - MDEXP (mod-data-export) Nolana release …
=> MDEXP-536 - Release 4.6.0

NEWS.md, pom.xml, src/main/java/org/folio/rest/impl/TenantReferenceAPI.java, src/main/resources/templates/db_scripts/schema.json
[MDEXP-568](https://issues.folio.org/browse/MDEXP-568) - mod-data-export: module release (MG)
=> MDEXP-568 - Release 4.5.2

PULL_REQUEST_TEMPLATE.md, src/main/resources/log4j2-json.properties, src/main/resources/log4j2.properties
[MDEXP-565](https://issues.folio.org/browse/MDEXP-565) - Logging improvement - Configuration
Logging should be improved for more productive troubleshooting.
Changed settings according to the requirements.
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment.  Communication is paramount if that is to be achieved, especially as the number …
=> MDEXP-565 - Logging improvement - Configuration

descriptors/ModuleDescriptor-template.json, src/main/java/org/folio/service/transformationfields/TransformationFieldsConfig.java, src/main/resources/rules/rulesDefault.json, src/test/resources/clients/inventory/get_instances_response.json, src/test/resources/mapping/expectedTransformationFields.json, src/test/resources/mapping/given_inventory_instance.json, src/test/resources/mockData/inventory/get_instance_response_in000005.json
[MDEXP-582](https://issues.folio.org/browse/MDEXP-582) - Align the module with API breaking change …
=> MDEXP-582 - Align the module with API breaking change

NEWS.md, pom.xml
[MDEXP-586](https://issues.folio.org/browse/MDEXP-586) - mod-data-export: module release
=> Release 4.7.0

src/main/java/org/folio/service/manager/input/InputDataManagerImpl.java, src/main/java/org/folio/service/profiles/mappingprofile/MappingProfileServiceImpl.java, src/test/java/org/folio/rest/impl/DataExportTest.java
[MDEXP-584](https://issues.folio.org/browse/MDEXP-584) - Holdings cannot be exported with custom mapping profile
In addition to the default mapping profile, users should be able to create a custom mapping profile where any supported holdings field can be included.
* Fixed export logic
Ideally all of the PRs involved in breaking …
=> MDEXP-584 - Holdings cannot be exported with custom mapping profile

NEWS.md, pom.xml, src/main/java/org/folio/service/manager/input/InputDataManagerImpl.java, src/main/java/org/folio/service/profiles/mappingprofile/MappingProfileServiceImpl.java, src/test/java/org/folio/rest/impl/DataExportTest.java
[MDEXP-591](https://issues.folio.org/browse/MDEXP-591) - mod-data-export: module release …
=> Release 4.7.1

README.md, src/main/java/org/folio/rest/impl/TenantReferenceAPI.java
[MDEXP-590](https://issues.folio.org/browse/MDEXP-590) - Add loadReference to README.md file
Data export comes with default mapping and job profiles for exporting instances, holdings and authority records. To enable those profiles the module need to be deployed with loadReference parameter set to true. This information is missing in README.md and the deployments might miss this configuration.
Updated README
- Are the JIRAs under …
=> MDEXP-590 - Add loadReference to README.md file

README.md, pom.xml, src/main/java/org/folio/service/export/storage/FolioS3ClientFactory.java, src/main/java/org/folio/service/export/storage/MinioClientFactory.java, src/main/java/org/folio/service/export/storage/MinioStorageServiceImpl.java, src/main/resources/minio.properties, src/test/java/org/folio/service/export/storage/MinioClientFactoryTest.java, src/test/java/org/folio/service/export/storage/MinioExportStorageServiceTest.java, src/test/resources/minio.properties
[MDEXP-588](https://issues.folio.org/browse/MDEXP-588) - Quick export: Job FAIL when all records was exported …
=> MDEXP-588 - Quick export: Job FAIL when all records was exported

src/main/java/org/folio/rest/impl/DataExportImpl.java, src/main/java/org/folio/service/job/JobExecutionServiceImpl.java, src/main/resources/templates/db_scripts/migration_scripts/add_job_profile_names.sql, src/main/resources/templates/db_scripts/schema.json, src/test/java/org/folio/rest/impl/DataExportTest.java, src/test/java/org/folio/service/job/JobExecutionServiceUnitTest.java
[MDEXP-605](https://issues.folio.org/browse/MDEXP-605) - Empty files are not sorted by “Job profile” on the "View all" page
When User sorts data export logs by "Job profile" column on the "View all" page the empty files are placed separately from other data export logs files and are not included in sorting by "Job profile" column (ascending, descending)
* Fixed job execution update logic
- Are the JIRAs under …
=> MDEXP-605 - Empty files are not sorted by “Job profile” on the "View all" page

src/main/java/org/folio/clients/ConsortiaClient.java, src/main/java/org/folio/clients/SourceRecordStorageClient.java, src/main/java/org/folio/util/ExternalPathResolver.java, src/test/java/org/folio/rest/impl/MockServer.java, src/test/java/org/folio/rest/impl/RestVerticleTestBase.java, src/test/java/org/folio/rest/impl/SourceRecordStorageTest.java, src/test/resources/mockData/user-tenants.json
[MDEXP-614](https://issues.folio.org/browse/MDEXP-614) - SRS-client with "shared" MARC records support …
=> MDEXP-614 - SRS-client with "shared" MARC records support

src/main/resources/db/changelog/changelog-master.xml, src/main/resources/db/changelog/changes/initial_schema.sql, src/main/resources/db/changelog/changes/initial_schema.xml
[MDEXP-624](https://issues.folio.org/browse/MDEXP-624) - Create liqubase scripts for new DB objects described in the design confluence page
Create liqubase scripts for new DB objects described in the design confluence page
Created schemas …
=> MDEXP-624 - Create liqubase scripts for new DB objects described in the design confluence page

Dockerfile, Jenkinsfile, pom.xml, src/test/java/org/folio/service/mapping/MappingServiceUnitTest.java
Update the module to Java 17 and identify issues.
Module updated to Java 17
While it's …
=> MDEXP-617: Update to Java 17. pom, Dockerfile, Jenkinsfile.

src/main/java/org/folio/clients/InventoryClient.java, src/main/java/org/folio/clients/SourceRecordStorageClient.java, src/main/java/org/folio/service/loader/RecordLoaderServiceImpl.java, src/test/java/org/folio/rest/impl/SourceRecordStorageTest.java, src/test/java/org/folio/service/loader/RecordLoaderServiceUnitTest.java
[MDEXP-637](https://issues.folio.org/browse/MDEXP-637) - Export shared MARC authorities
MARC authorities should support ECS.
Already implemented approach is applicable for Authorities case.
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment.  Communication is paramount if …
=> MDEXP-637 - Export shared MARC authorities

src/main/resources/templates/db_scripts/migration_scripts/update_failed.sql, src/main/resources/templates/db_scripts/schema.json
[MDEXP-625](https://issues.folio.org/browse/MDEXP-625) - Migration script for old job executions
Need to create a migration script for old job executions.
Write sql script.
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment.  Communication is paramount if that is to be …
=> MDEXP-625 - Migration script for old job executions

src/main/resources/postgres-conf.json, src/main/resources/templates/db_scripts/migration_scripts/add_user_id_to_job_execution_run_by.sql, src/main/resources/templates/db_scripts/schema.json
[MDEXP-643](https://issues.folio.org/browse/MDEXP-643) - Migration scripts for adding user id to jobExecution schema
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment.  Communication is paramount if that is to be achieved, especially as the number of intermodule and …
=> MDEXP-643 - Migration scripts for adding user id to jobExecution schema

pom.xml
Update version of folio-s3-client to 1.1.0 to fix build failure
Updating dependency version …
=> Update version of folio-s3-client in pom.xml

src/main/java/org/folio/clients/BaseConcurrentClient.java
Follow-up to [PR#379](https://github.com/folio-org/mod-data-export/pull/379) with improvement/optimization of retrieving authorities/instances logic.
=> MDEXP-637 - Improve retrieving authorities/instances logic

descriptors/ModuleDescriptor-template.json
[MDEXP-633](https://issues.folio.org/browse/MDEXP-633) - inconsistent Data export results by Admin and User with data export permissions …
=> MDEXP-633 - update permissions

NEWS.md, pom.xml
[MDEXP-650](https://issues.folio.org/browse/MDEXP-650) - mod-data-export: module release …
=> MDEXP-650 - Release 4.8.0

NEWS.md, pom.xml
[MDEXP-656](https://issues.folio.org/browse/MDEXP-656) - mod-data-export: module release 
Release 4.8.1 version. …
=> MDEXP-656 - mod-data-export: module release

src/main/java/org/folio/service/file/reader/LocalStorageCsvSourceReader.java, src/main/java/org/folio/service/file/reader/SourceReader.java, src/main/java/org/folio/service/job/JobExecutionService.java, src/main/java/org/folio/service/job/JobExecutionServiceImpl.java, src/main/java/org/folio/service/manager/export/ExportManagerImpl.java, src/main/java/org/folio/service/manager/export/ExportPayload.java, src/main/java/org/folio/service/manager/input/InputDataManagerImpl.java, src/test/java/org/folio/service/file/reader/LocalStorageCsvSourceReaderUnitTest.java, src/test/java/org/folio/service/job/JobExecutionServiceUnitTest.java, src/test/java/org/folio/service/manager/input/InputDataManagerUnitTest.java
[MDEXP-557](https://issues.folio.org/browse/MDEXP-557) - "Failed" column is not populated on the "Logs" pane of Data Export
Jobs that were completed with status "Failed" and "Completed with errors" don't have populated number of failed UUIDs in the "Failed" column
Add invalidUUIDs field to ExportPayload, added number of invalid UUIDs to totalCount. …
=> MDEXP-557 - "Failed" column is not populated on the "Logs" pane of Data Export

src/main/resources/templates/db_scripts/migration_scripts/add_job_profile_names.sql, src/main/resources/templates/db_scripts/migration_scripts/add_user_id_to_job_execution_run_by.sql, src/main/resources/templates/db_scripts/migration_scripts/update_failed.sql, src/main/resources/templates/db_scripts/schema.json
[MDEXP-625](https://issues.folio.org/browse/MDEXP-625) - Fix migration script
Fix migration script.
Add white spaces before and after scripts.
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment.  Communication is paramount if that is to be achieved, especially as the number …
=> MDEXP-625 - Fix migration script

NEWS.md, pom.xml, src/main/java/org/folio/service/file/reader/LocalStorageCsvSourceReader.java, src/main/java/org/folio/service/file/reader/SourceReader.java, src/main/java/org/folio/service/job/JobExecutionService.java, src/main/java/org/folio/service/job/JobExecutionServiceImpl.java, src/main/java/org/folio/service/manager/export/ExportManagerImpl.java, src/main/java/org/folio/service/manager/export/ExportPayload.java, src/main/java/org/folio/service/manager/input/InputDataManagerImpl.java, src/test/java/org/folio/service/file/reader/LocalStorageCsvSourceReaderUnitTest.java, src/test/java/org/folio/service/job/JobExecutionServiceUnitTest.java, src/test/java/org/folio/service/manager/input/InputDataManagerUnitTest.java
[MDEXP-661](https://issues.folio.org/browse/MDEXP-661) - mod-data-export: module release
Release v4.8.2. …
=> MDEXP-661 - Release 4.8.2

descriptors/ModuleDescriptor-template.json
[MDEXP-660](https://issues.folio.org/browse/MDEXP-660) - Specify missing interface dependencies
mod-data-export makes calls to the following endpoints, but does not declare the corresponding interfaces as required (or optional) in its module descriptor
Add interfaces. …
=> MDEXP-660 - Specify missing interface dependencies

pom.xml, src/main/java/org/folio/service/export/storage/MinioStorageServiceImpl.java, src/test/java/org/folio/service/export/storage/MinioExportStorageServiceTest.java
=> MDEXP-658 bump up folio-s3-client

NEWS.md, descriptors/ModuleDescriptor-template.json, pom.xml, src/main/java/org/folio/clients/InventoryClient.java, src/main/java/org/folio/service/logs/ErrorLogServiceImpl.java, src/main/java/org/folio/service/manager/export/strategy/AbstractExportStrategy.java, src/main/java/org/folio/util/ErrorCode.java, src/test/java/org/folio/service/logs/ErrorLogServiceUnitTest.java, src/test/java/org/folio/service/manager/export/InstanceExportStrategyUnitTest.java
[MDEXP-665](https://issues.folio.org/browse/MDEXP-665) - mod-data-export: module release
=> Release 4.8.3

NEWS.md, pom.xml, src/main/java/org/folio/service/export/storage/MinioStorageServiceImpl.java, src/test/java/org/folio/service/export/storage/MinioExportStorageServiceTest.java
=> Release 4.8.4

NEWS.md, pom.xml, src/main/java/org/folio/dao/JobExecutionDao.java, src/main/java/org/folio/dao/impl/JobExecutionDaoImpl.java, src/main/java/org/folio/service/file/upload/FileUploadServiceImpl.java, src/main/java/org/folio/service/job/JobExecutionServiceImpl.java, src/test/java/org/folio/service/job/JobExecutionServiceUnitTest.java
[MDEXP-671](https://issues.folio.org/browse/MDEXP-671) - mod-data-export: module release
=> Release 4.8.6

NEWS.md, pom.xml
[MDEXP-674](https://issues.folio.org/browse/MDEXP-674) - mod-data-export: module release
folio-s3-client upgrade …
=> Release v4.8.7

src/main/java/org/folio/dataexp/client/ConsortiaClient.java, src/main/java/org/folio/dataexp/domain/dto/UserTenant.java, src/main/java/org/folio/dataexp/domain/dto/UserTenantCollection.java, src/main/java/org/folio/dataexp/repository/MarcAuthorityRecordRepository.java, src/main/java/org/folio/dataexp/service/ConsortiaService.java, src/main/java/org/folio/dataexp/service/export/ExportStrategyFactory.java, src/main/java/org/folio/dataexp/service/export/strategies/AuthorityExportStrategy.java, src/main/resources/db/changelog/changes/initial_schema.sql, src/test/java/org/folio/dataexp/service/ConsortiaServiceTest.java, src/test/java/org/folio/dataexp/service/export/strategies/AuthorityExportStrategyTest.java, src/test/resources/init_mod_source_record_storage.sql
[MDEXP-627](https://issues.folio.org/browse/MDEXP-627) - /data-export/export: Authority Strategy
Existing AuthorityStrategy https://github.com/folio-org/mod-data-export/blob/master/src/main/java/org/folio/service/manager/export/strategy/AuthorityExportStrategyImpl.java should be implemented and integrated in the business flow with using interface https://github.com/folio-org/mod-data-export/blob/mdexp-spring/src/main/java/org/folio/dataexp/service/export/strategies/ExportStrategy.java.
- What other modules will these changes …
=> MDEXP-627 - /data-export/export: Authority Strategy

src/main/java/org/folio/dataexp/config/ExportConfiguration.java, src/main/java/org/folio/dataexp/domain/entity/ItemEntity.java, src/main/java/org/folio/dataexp/service/CommonExportFails.java, src/main/java/org/folio/dataexp/service/DataExportService.java, src/main/java/org/folio/dataexp/service/InputFileProcessor.java, src/main/java/org/folio/dataexp/service/SingleFileProcessor.java, src/main/java/org/folio/dataexp/service/SingleFileProcessorAsync.java, src/main/java/org/folio/dataexp/service/export/ExportExecutor.java, src/main/java/org/folio/dataexp/service/export/strategies/AuthorityExportStrategy.java, src/main/java/org/folio/dataexp/service/export/strategies/HoldingsExportStrategy.java, src/main/java/org/folio/dataexp/service/file/upload/FileUploadServiceImpl.java, src/main/java/org/folio/dataexp/service/logs/ErrorLogService.java, src/main/resources/swagger.api/data-export.yaml, src/test/java/org/folio/dataexp/service/SingleFileProcessorTest.java, src/test/java/org/folio/dataexp/service/export/ExportExecutorTest.java, src/test/java/org/folio/dataexp/service/export/strategies/AuthorityExportStrategyTest.java, src/test/java/org/folio/dataexp/service/export/strategies/HoldingsExportStrategyTest.java, src/test/java/org/folio/dataexp/service/logs/ErrorLogServiceTest.java
[MDEXP-628](https://issues.folio.org/browse/MDEXP-628) - /data-export/export: Holdings Strategy …
=> MDEXP-628 - /data-export/export: Holdings Strategy

src/main/java/org/folio/dataexp/service/file/upload/FileUploadServiceImpl.java
[MDEXP-640](https://issues.folio.org/browse/MDEXP-640) - Data-Export: Rewrite/clean up existing and non-changed logic
* Fixed sourcePath value for fileDefinition
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment.  Communication is paramount if that is to be achieved, …
=> MDEXP-640 - Data-Export: Rewrite/clean up existing and non-changed logic

src/main/java/org/folio/dataexp/controllers/JobExecutionsController.java, src/main/java/org/folio/dataexp/service/FileDefinitionsService.java, src/main/java/org/folio/dataexp/service/InputFileProcessor.java, src/main/java/org/folio/dataexp/service/SlicerProcessor.java, src/main/java/org/folio/dataexp/service/StorageCleanUpService.java, src/main/java/org/folio/dataexp/service/file/download/FileDownloadService.java, src/main/java/org/folio/dataexp/service/file/download/FileDownloadServiceImpl.java, src/main/java/org/folio/dataexp/service/file/upload/FilesUploadService.java, src/main/java/org/folio/dataexp/service/file/upload/FilesUploadServiceImpl.java, src/main/java/org/folio/dataexp/util/S3FilePathUtils.java, src/test/java/org/folio/dataexp/service/FileDefinitionsServiceTest.java, src/test/java/org/folio/dataexp/service/InputFileProcessorTest.java, src/test/java/org/folio/dataexp/service/SlicerProcessorTest.java, src/test/java/org/folio/dataexp/service/StorageCleanUpServiceTest.java, src/test/java/org/folio/dataexp/service/file/download/FilesDownloadServiceTest.java, src/test/java/org/folio/dataexp/service/file/upload/FilesUploadServiceTest.java
[MDEXP-642](https://issues.folio.org/browse/MDEXP-642) - Files Download: Rewrite/clean up existing and non-changed logic
Files Download: Rewrite/clean up existing and non-changed logic.
Non-affected APIs from mod-data-expor/data-export  [https://dev.folio.org/reference/api/#mod-data-export] should be rewritten to utilise their own new Services and Controllers. The following endpoints should be refactored:
* [GET /data-export/job-executions/\{jobExecutionId}/download/\{exportFileId}|https://s3.amazonaws.com/foliodocs/api/mod-data-export/p/dataExport.html#data_export_job_executions__jobexecutionid__download__exportfileid__get]
- Does this …
=> MDEXP-642 - Files Download: Rewrite/clean up existing and non-changed logic

descriptors/ModuleDescriptor-template.json, src/main/java/org/folio/dataexp/controllers/ConfigurationController.java, src/main/java/org/folio/dataexp/domain/entity/ConfigurationEntity.java, src/main/java/org/folio/dataexp/exception/DataExportExceptionHandler.java, src/main/java/org/folio/dataexp/exception/configuration/SliceSizeValidationException.java, src/main/java/org/folio/dataexp/repository/ConfigurationRepository.java, src/main/java/org/folio/dataexp/service/ConfigurationService.java, src/main/java/org/folio/dataexp/service/DataExportService.java, src/main/java/org/folio/dataexp/service/DataExportTenantService.java, src/main/java/org/folio/dataexp/service/FileDefinitionsService.java, src/main/java/org/folio/dataexp/service/SlicerProcessor.java, src/main/java/org/folio/dataexp/service/validators/ConfigurationValidator.java, src/main/java/org/folio/dataexp/service/validators/DataExportRequestValidator.java, src/main/java/org/folio/dataexp/service/validators/FileDefinitionValidator.java, src/main/resources/db/changelog/changelog-master.xml, src/main/resources/db/changelog/changes/add_config.sql, src/main/resources/db/changelog/changes/add_config.xml, src/main/resources/swagger.api/data-export.yaml, src/main/resources/swagger.api/examples/configuration/config.json, src/main/resources/swagger.api/schemas/configuration/config.json, src/test/java/org/folio/dataexp/controllers/ConfigurationControllerTest.java, src/test/java/org/folio/dataexp/repository/ConfigurationRepositoryTest.java, src/test/java/org/folio/dataexp/service/ConfigurationServiceTest.java, src/test/java/org/folio/dataexp/service/DataExportServiceTest.java, src/test/java/org/folio/dataexp/service/FileDefinitionsServiceTest.java, src/test/java/org/folio/dataexp/service/validators/ConfigurationValidatorTest.java, src/test/java/org/folio/dataexp/service/validators/DataExportRequestValidatorTest.java, src/test/java/org/folio/dataexp/service/validators/FileDefinitionValidatorTest.java
[MDEXP-634](https://issues.folio.org/browse/MDEXP-634) - Slicer component: configuration support
Slicer component supports size of file as hardcoded value. This value needs to be configured.
Add config_data table with key/value columns.
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing …
=> MDEXP-634 - Slicer component: configuration support

descriptors/ModuleDescriptor-template.json, pom.xml, src/main/java/org/folio/dataexp/domain/entity/InstanceWithHridEntity.java, src/main/java/org/folio/dataexp/repository/CentralEntityRepository.java, src/main/java/org/folio/dataexp/repository/HoldingsRecordEntityRepository.java, src/main/java/org/folio/dataexp/repository/InstanceCentralTenantRepository.java, src/main/java/org/folio/dataexp/repository/InstanceWithHridEntityRepository.java, src/main/java/org/folio/dataexp/repository/ItemEntityRepository.java, src/main/java/org/folio/dataexp/repository/MarcInstanceRecordRepository.java, src/main/java/org/folio/dataexp/service/export/Constants.java, src/main/java/org/folio/dataexp/service/export/ExportExecutor.java, src/main/java/org/folio/dataexp/service/export/strategies/AbstractExportStrategy.java, src/main/java/org/folio/dataexp/service/export/strategies/AuthorityExportStrategy.java, src/main/java/org/folio/dataexp/service/export/strategies/ExportIdentifiersForDuplicateErrors.java, src/main/java/org/folio/dataexp/service/export/strategies/HoldingsExportStrategy.java, src/main/java/org/folio/dataexp/service/export/strategies/InstancesExportStrategy.java, src/main/java/org/folio/dataexp/service/export/strategies/JsonToMarcConverter.java, src/main/java/org/folio/dataexp/service/export/strategies/MarcFields.java, src/main/java/org/folio/dataexp/service/export/strategies/RuleFactory.java, src/main/java/org/folio/dataexp/service/logs/ErrorLogService.java, src/main/java/org/folio/dataexp/util/ErrorCode.java, src/main/resources/db/changelog/changes/initial_schema.sql, src/main/resources/rules/rulesDefault.json, src/test/java/org/folio/dataexp/service/export/ExportExecutorTest.java, src/test/java/org/folio/dataexp/service/export/strategies/AbstractExportStrategyTest.java, src/test/java/org/folio/dataexp/service/export/strategies/AuthorityExportStrategyTest.java, src/test/java/org/folio/dataexp/service/export/strategies/HoldingsExportStrategyTest.java, src/test/java/org/folio/dataexp/service/export/strategies/InstancesExportStrategyTest.java, src/test/java/org/folio/dataexp/service/export/strategies/JsonToMarcConverterTest.java
[MDEXP-626 ](https://issues.folio.org/browse/MDEXP-626) - /data-export/export: Instances Strategy …
=> MDEXP-626 - /data-export/export: Instances Strategy

README.md, src/main/java/org/folio/dataexp/service/DataExportTenantService.java, src/main/resources/application.yml, src/test/java/org/folio/dataexp/BaseDataExportInitializer.java
https://folio-org.atlassian.net/browse/MDEXP-684
Views migration should be reworked to skip env variable usage.
Introduce setup of system var value (equal to tenant value) at the time of the general tenant upgrade flow
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment. …
=> MDEXP-684: Avoid manual configuration for data-export

src/main/resources/db/changelog/changes/initial_schema.sql
=> MDEXP-627 remove v_authority view from migration

descriptors/ModuleDescriptor-template.json, pom.xml, src/main/java/org/folio/dataexp/client/ConfigurationEntryClient.java, src/main/java/org/folio/dataexp/service/ConfigurationEntryService.java, src/main/java/org/folio/dataexp/service/ConfigurationService.java, src/main/java/org/folio/dataexp/service/DataExportTenantService.java, src/main/java/org/folio/dataexp/service/logs/ErrorLogService.java, src/main/resources/application.yml, src/main/resources/swagger.api/data-export.yaml, src/main/resources/swagger.api/schemas/common/diagnostic.json, src/main/resources/swagger.api/schemas/common/facet.json, src/main/resources/swagger.api/schemas/common/facetValue.json, src/main/resources/swagger.api/schemas/common/resultInfo.json, src/main/resources/swagger.api/schemas/configuration/configurationEntry.json, src/main/resources/swagger.api/schemas/configuration/configurationEntryCollection.json, src/test/java/org/folio/dataexp/BaseDataExportInitializer.java, src/test/java/org/folio/dataexp/controllers/ConfigurationControllerTest.java, src/test/java/org/folio/dataexp/repository/ConfigurationRepositoryTest.java
https://folio-org.atlassian.net/browse/MDEXP-685
Remove manual configuration for Inventory record link variable
the folio host value is taken from the configurations/entries by the FOLIO_HOST - code
and stored in _mod_data_export.config_data - table at the time of the tenant setup.
The app is designed to take it from the DB/hibernate cache at any time, it needs
- Do PRs exist for these …
=> MDEXP-685: Remove manual configuration for Inventory record link variable

src/main/java/org/folio/dataexp/controllers/JobProfileController.java, src/main/java/org/folio/dataexp/controllers/MappingProfileController.java, src/main/resources/application.yml
https://folio-org.atlassian.net/browse/MDEXP-689
fix for NPE at the time of Mapping Profile and Job Profile update flow
The metadata is generated based on the existing MappingProfileEntity/JobProfileEntity metadata
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment. …
=> MDEXP-689: fix for NPE at the time of Mapping Profile update flow

src/main/java/org/folio/dataexp/service/DataExportAllService.java, src/main/resources/db/changelog/changes/add_export_all.sql
[MDEXP-621](https://issues.folio.org/browse/MDEXP-621) - Export all endpoint
Fix custom duplicated, improve naming.
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment.  Communication is paramount if that is to be achieved, especially as the number of intermodule and …
=> MDEXP-621 - Export all endpoint 

descriptors/ModuleDescriptor-template.json, src/main/java/org/folio/dataexp/domain/entity/JobExecutionExportFilesEntity.java, src/main/java/org/folio/dataexp/repository/MarcInstanceRecordRepository.java, src/main/java/org/folio/dataexp/service/export/ExportExecutor.java, src/main/java/org/folio/dataexp/service/export/strategies/AbstractExportStrategy.java, src/main/java/org/folio/dataexp/service/export/strategies/AuthorityExportAllStrategy.java, src/main/java/org/folio/dataexp/service/export/strategies/HoldingsExportAllStrategy.java, src/main/java/org/folio/dataexp/service/export/strategies/InstancesExportAllStrategy.java
[MDEXP-641](https://folio-org.atlassian.net/browse/MDEXP-641)
Fix permission for consortia, completed_with_errors for export all, missed 3 columns for marcs
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment.  Communication is paramount if that is to be achieved, especially …
=> MDEXP-641 - Quick-Export: Rewrite/clean up existing and non-changed logic

src/main/java/org/folio/dataexp/repository/MarcRecordEntityRepository.java, src/main/java/org/folio/dataexp/service/export/strategies/InstancesExportStrategy.java, src/test/java/org/folio/dataexp/service/QuickExportServiceTest.java, src/test/java/org/folio/dataexp/service/export/strategies/InstancesExportStrategyTest.java
[MDEXP-690](https://folio-org.atlassian.net/browse/MDEXP-690) - Export MARC Instances with edited SRS
In new approach for Data export edit MARC Instance via Edit MARC bib affects Data export result as each SRS version is reported as duplicated SRS.
Return only with Actual state.
Ideally all of the PRs involved in breaking changes would be merged in the …
=> MDEXP-690 - Export MARC Instances with edited SRS

src/main/java/org/folio/dataexp/service/DataExportService.java, src/main/java/org/folio/dataexp/service/export/ExportExecutor.java, src/main/java/org/folio/dataexp/service/export/strategies/AbstractExportStrategy.java, src/test/java/org/folio/dataexp/BaseDataExportInitializer.java, src/test/java/org/folio/dataexp/service/DataExportServiceTest.java
[MDEXP-677](https://folio-org.atlassian.net/browse/MDEXP-677) - Files upload flow rework …
=> MDEXP-677 - fix empty export file name

src/main/java/org/folio/dataexp/controllers/JobProfileController.java, src/main/java/org/folio/dataexp/repository/JobProfileEntityCqlRepository.java, src/main/resources/swagger.api/data-export.yaml, src/test/java/org/folio/dataexp/controllers/JobProfileControllerTest.java
https://folio-org.atlassian.net/browse/MDEXP-711
Return list of the job profiles used in completed jobs
Request for the data against the job_executions table provides such info.
SELECT DISTINCT job_profile_id, jsonb ->> 'jobProfileName' FROM job_executions
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid …
=> MDEXP-711: Return list of the job profiles used in completed jobs.

src/main/java/org/folio/dataexp/repository/ExportIdEntityRepository.java, src/main/java/org/folio/dataexp/service/StorageCleanUpService.java, src/main/java/org/folio/dataexp/service/export/ExportExecutor.java, src/test/java/org/folio/dataexp/service/export/ExportExecutorTest.java
[MDEXP-720](https://folio-org.atlassian.net/browse/MDEXP-720) - Clean job_executions_export_ids table after export for spring base module …
=> MDEXP-720 - Clean job_executions_export_ids table after export for spring base module

src/main/java/org/folio/dataexp/service/CommonExportFails.java, src/main/java/org/folio/dataexp/service/InputFileProcessor.java, src/main/java/org/folio/dataexp/service/logs/ErrorLogService.java, src/main/java/org/folio/dataexp/service/validators/DataExportRequestValidator.java, src/main/java/org/folio/dataexp/service/validators/FileDefinitionValidator.java, src/test/java/org/folio/dataexp/service/validators/DataExportRequestValidatorTest.java, src/test/java/org/folio/dataexp/service/validators/FileDefinitionValidatorTest.java
[MDEXP-712](https://folio-org.atlassian.net/browse/MDEXP-712) - Implement the proper error message value
Implement the proper error message value …
=> MDEXP-712 - Implement the proper error message value

src/main/java/org/folio/dataexp/controllers/JobProfileController.java
[DEXP-711](https://folio-org.atlassian.net/browse/MDEXP-711) - nonNull checks
While it's …
=> MDEXP-711 - nonNull checks

src/main/java/org/folio/dataexp/repository/HoldingsRecordEntityRepository.java, src/main/java/org/folio/dataexp/repository/InstanceEntityRepository.java, src/main/java/org/folio/dataexp/repository/MarcAuthorityRecordAllRepository.java, src/main/java/org/folio/dataexp/service/DataExportService.java, src/main/java/org/folio/dataexp/service/export/strategies/AbstractExportStrategy.java
[MDEXP-713](https://folio-org.atlassian.net/browse/MDEXP-713) - Provide accurate progress information on Export all jobs
Set 'total' value for Progress of Export all.
Fetch count(id) from database. …
=> MDEXP-713 - Provide accurate progress information on Export all jobs

descriptors/ModuleDescriptor-template.json, src/main/java/org/folio/dataexp/controllers/RelatedUsersController.java, src/main/resources/swagger.api/data-export.yaml, src/main/resources/swagger.api/examples/relatedUser.json, src/main/resources/swagger.api/examples/relatedUserCollection.json, src/main/resources/swagger.api/schemas/relatedUser.json, src/main/resources/swagger.api/schemas/relatedUserCollection.json, src/test/java/org/folio/dataexp/controllers/RelatedUsersControllerTest.java
[MDEXP-110](https://folio-org.atlassian.net/browse/MDEXP-110) - Return list of users who run the completed jobs
In the UI user will be able to filter completed export jobs by users who run those jobs. …
=> MDEXP-110 - Return list of users who run the completed jobs

src/main/java/org/folio/dataexp/service/transformationfields/ReferenceDataService.java, src/main/resources/swagger.api/schemas/referencedata/campuses.json, src/main/resources/swagger.api/schemas/referencedata/institutions.json, src/main/resources/swagger.api/schemas/referencedata/libraries.json, src/test/java/org/folio/dataexp/service/transformationfields/ReferenceDataServiceTest.java
[MDEXP-725](https://folio-org.atlassian.net/browse/MDEXP-725) - Reference data is not included in export/fail export
Location units data is not included in export
Fixed schemas
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment.  Communication is paramount if that is to be …
=> MDEXP-725 - Reference data is not included in export/fail export

pom.xml, src/main/java/org/folio/dataexp/controllers/JobExecutionsController.java, src/main/java/org/folio/dataexp/controllers/JobProfileController.java, src/main/java/org/folio/dataexp/controllers/LogsController.java, src/main/java/org/folio/dataexp/controllers/MappingProfileController.java, src/main/java/org/folio/dataexp/service/logs/ErrorLogService.java, src/main/resources/db/changelog/changes/add_config.xml, src/main/resources/db/changelog/changes/add_export_all.xml, src/main/resources/db/changelog/changes/enrich_tables.xml, src/main/resources/db/changelog/changes/init_procedures.xml, src/main/resources/db/changelog/changes/initial_schema.xml, src/main/resources/db/changelog/changes/slice_records_all_ids.xml, src/test/java/org/folio/dataexp/controllers/JobExecutionsControllerTest.java, src/test/java/org/folio/dataexp/controllers/JobProfileControllerTest.java, src/test/java/org/folio/dataexp/controllers/LogsControllerTest.java, src/test/java/org/folio/dataexp/controllers/MappingProfileControllerTest.java, src/test/java/org/folio/dataexp/service/logs/ErrorLogServiceTest.java
[MDEXP-724](https://folio-org.atlassian.net/browse/MDEXP-724) - mod-data-export: spring upgrade
Upgrade spring.
spring-boot-starter-parent from 3.0.7 to **3.2.3**
folio-spring-base from 6.1.0 to **8.1.0**
added folio-spring-cql **8.1.0**
from hypersistence-utils-hibernate-60 3.5.0 to hypersistence-utils-hibernate-63 to **3.7.3**
Ideally all of the PRs …
=> MDEXP-724 - mod-data-export: spring upgrade

src/main/java/org/folio/dataexp/service/ConfigurationEntryService.java
[MDEXP-735](https://folio-org.atlassian.net/browse/MDEXP-735) - Avoid exception if configuration was not found
Configuration Service should not throw NotFoundException if configuration was not found. ConfigurationEntry with empty value should be returned instead.
Updated logic
Ideally all of the PRs involved in breaking changes would be merged in the …
=> MDEXP-735 - Avoid exception if configuration was not found

src/main/java/org/folio/dataexp/service/DataExportService.java
[MDEXP-736](https://folio-org.atlassian.net/browse/MDEXP-736) - Date-time displayed in progress bar and "Started running" column
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment.  Communication is paramount if that is to be achieved, especially as the number of intermodule …
=> MDEXP-736 - update started date

src/main/java/org/folio/dataexp/service/export/S3ExportsUploader.java, src/test/java/org/folio/dataexp/service/export/S3ExportsUploaderTest.java
=> MDEXP-677 fix OOM during S3 upload

src/main/java/org/folio/dataexp/controllers/MappingProfileController.java, src/main/java/org/folio/dataexp/exception/DataExportExceptionHandler.java, src/main/java/org/folio/dataexp/exception/mapping/profile/MappingProfileTransformationEmptyException.java, src/main/java/org/folio/dataexp/exception/mapping/profile/MappingProfileTransformationPatternException.java, src/main/java/org/folio/dataexp/service/MappingProfileService.java, src/main/resources/swagger.api/data-export.yaml, src/main/resources/swagger.api/schemas/profiles/transformations.json, src/test/java/org/folio/dataexp/controllers/MappingProfileControllerTest.java, src/test/java/org/folio/dataexp/service/MappingProfileServiceTest.java
[MDEXP-741](https://folio-org.atlassian.net/browse/MDEXP-741) - Data export should provide UnprocessableEntity response according karate scenarios …
=> MDEXP-741 - Data export should provide UnprocessableEntity response according karate scenarios

src/main/java/org/folio/dataexp/service/export/S3ExportsUploader.java
[MDEXP-746](https://folio-org.atlassian.net/browse/MDEXP-746) - Files large 2Gb cannot be completely saved
Large files cannot be completely saved. 
Replace is.available() to zip/file size.
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment.  Communication is paramount if …
=> MDEXP-746 - Files large 2Gb cannot be completely saved

NEWS.md, pom.xml, src/main/java/org/folio/dataexp/service/export/S3ExportsUploader.java
=> Release 5.0.2

src/main/java/org/folio/dataexp/domain/entity/AuditInstanceEntity.java, src/main/java/org/folio/dataexp/repository/AuditInstanceEntityRepository.java, src/main/java/org/folio/dataexp/service/export/Constants.java, src/main/java/org/folio/dataexp/service/export/S3ExportsUploader.java, src/main/java/org/folio/dataexp/service/export/strategies/AbstractExportStrategy.java, src/main/java/org/folio/dataexp/service/export/strategies/InstancesExportAllStrategy.java, src/main/java/org/folio/dataexp/service/export/strategies/InstancesExportStrategy.java, src/main/resources/application.yml, src/main/resources/db/changelog/changelog-master.xml, src/main/resources/db/changelog/changes/audit_instance_view.sql, src/main/resources/db/changelog/changes/audit_instance_view.xml, src/test/java/org/folio/dataexp/service/export/strategies/AbstractExportStrategyTest.java, src/test/java/org/folio/dataexp/service/export/strategies/InstancesExportAllStrategyTest.java, src/test/java/org/folio/dataexp/service/export/strategies/InstancesExportStrategyTest.java, src/test/resources/init_mod_inventory_storage.sql
[MDEXP-740](https://folio-org.atlassian.net/browse/MDEXP-740) - Export all - Number of duplicates reported in "Failed" column doesn't correspond with the number of duplicates on Error logs page
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment.  Communication is paramount …
=> MDEXP-740 - Export all - Number of duplicates reported in "Failed" column doesn't correspond with the number of duplicates on Error logs page

.gitignore, README.md, src/main/java/org/folio/dataexp/service/SingleFileProcessor.java, src/main/java/org/folio/dataexp/service/export/S3ExportsUploader.java, src/main/java/org/folio/dataexp/service/export/strategies/AbstractExportStrategy.java, src/main/java/org/folio/dataexp/util/Constants.java, src/main/java/org/folio/dataexp/util/S3FilePathUtils.java, src/main/resources/application.yml, src/test/java/org/folio/dataexp/service/export/LocalStorageWriterTest.java, src/test/java/org/folio/dataexp/service/export/S3ExportsUploaderTest.java, src/test/java/org/folio/dataexp/util/S3FilePathUtilsTest.java
[MDEXP-750](https://folio-org.atlassian.net/browse/MDEXP-750) - Create environment variable for volume to store files in mod-data-export …
=> MDEXP-750 - Create environment variable for volume to store files in mod-data-export

NEWS.md, pom.xml
[MDEXP-754](https://folio-org.atlassian.net/browse/MDEXP-754) - Release 5.0.3
=> MDEXP-754 - Release 5.0.3

NEWS.md, pom.xml, src/main/resources/db/changelog/changelog-master.xml, src/main/resources/db/changelog/changes/delete_error_logs_empty_job_execution_id.sql, src/main/resources/db/changelog/changes/delete_error_logs_empty_job_execution_id.xml, src/main/resources/db/changelog/changes/update_default_authority_profiles.sql, src/main/resources/db/changelog/changes/update_default_authority_profiles.xml
=>  Release 5.0.4

src/main/java/org/folio/dataexp/service/export/strategies/InstancesExportStrategy.java, src/main/java/org/folio/dataexp/service/export/strategies/RuleFactory.java, src/main/java/org/folio/dataexp/util/Constants.java, src/main/resources/swagger.api/schemas/profiles/mappingProfile.json, src/test/java/org/folio/dataexp/service/export/strategies/RuleFactoryTest.java
[MDEXP-742](https://folio-org.atlassian.net/browse/MDEXP-742) - Exclude fields from export records
In some exports, libraries need to suppress MARC fields that might contain data relevant only for the libraries. 
* Implemented logic
* Added unit tests
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking …
=> MDEXP-742 - Exclude fields from export records

src/main/java/org/folio/dataexp/client/SourceStorageClient.java, src/main/java/org/folio/dataexp/domain/dto/MarcRecordIdentifiersPayload.java, src/main/java/org/folio/dataexp/domain/dto/MarcRecordsIdentifiersResponse.java
[MDEXP-730](https://folio-org.atlassian.net/browse/MDEXP-730) - MARC Search Client
While …
=> MDEXP-730 - MARC Search Client

src/main/java/org/folio/dataexp/service/export/strategies/AbstractExportStrategy.java, src/main/java/org/folio/dataexp/service/export/strategies/AuthorityExportAllStrategy.java, src/main/java/org/folio/dataexp/service/export/strategies/HoldingsExportAllStrategy.java, src/main/java/org/folio/dataexp/service/export/strategies/InstancesExportAllStrategy.java, src/main/java/org/folio/dataexp/service/export/strategies/InstancesExportStrategy.java, src/test/java/org/folio/dataexp/service/export/strategies/InstancesExportAllStrategyTest.java, src/test/java/org/folio/dataexp/service/export/strategies/InstancesExportStrategyTest.java
[MDEXP-756](https://folio-org.atlassian.net/browse/MDEXP-756) - "Error.recordIsTooLong" error is not displayed on Error log page for Custom profile with SRS
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment.  Communication is paramount if that is to be achieved, especially …
=> MDEXP-756 - "Error.recordIsTooLong" error is not displayed on Error log page for Custom profile with SRS

README.md, src/main/java/org/folio/dataexp/service/InputFileProcessor.java, src/main/java/org/folio/dataexp/service/export/strategies/AuthorityExportStrategy.java, src/main/java/org/folio/dataexp/service/export/strategies/GeneratedMarcResult.java, src/main/java/org/folio/dataexp/service/export/strategies/HoldingsExportAllStrategy.java, src/main/java/org/folio/dataexp/service/export/strategies/HoldingsExportStrategy.java, src/main/java/org/folio/dataexp/service/export/strategies/InstancesExportAllStrategy.java, src/main/java/org/folio/dataexp/service/export/strategies/InstancesExportStrategy.java, src/test/java/org/folio/dataexp/service/InputFileProcessorTest.java, src/test/java/org/folio/dataexp/service/export/strategies/AbstractExportStrategyTest.java, src/test/java/org/folio/dataexp/service/export/strategies/HoldingsExportStrategyTest.java, src/test/java/org/folio/dataexp/service/export/strategies/InstancesExportStrategyTest.java, src/test/resources/upload_duplicated.csv
[MDEXP-757](https://folio-org.atlassian.net/browse/MDEXP-757) - Not all errors listed have details in error logs …
=> MDEXP-757 - Not all errors listed have details in error logs

descriptors/ModuleDescriptor-template.json
[MDEXP-751](https://folio-org.atlassian.net/browse/MDEXP-751) - Export Holdings with Default Export Profile from Central Tenant
Add missing permission.
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment.  Communication is paramount if that is to be achieved, especially as …
=> MDEXP-751 - Export Holdings with Default Export Profile from Central Tenant

descriptors/ModuleDescriptor-template.json
[MDEXP-767](https://folio-org.atlassian.net/browse/MDEXP-767)
Add "7.0" holding-storage version to be synchronized with inventory-storage module 
Increased holding-storage version from 6.0 to 7.0
- Are the JIRAs under active development?
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment.  Communication is paramount …
=> MDEXP-767 - added "7.0" holding-storage version

src/main/java/org/folio/dataexp/repository/MarcRecordEntityRepository.java, src/main/java/org/folio/dataexp/service/export/strategies/HoldingsExportStrategy.java, src/main/java/org/folio/dataexp/service/export/strategies/InstancesExportStrategy.java, src/main/java/org/folio/dataexp/service/transformationfields/ReferenceDataService.java, src/main/resources/application.yml, src/test/java/org/folio/dataexp/service/export/strategies/HoldingsExportStrategyTest.java, src/test/java/org/folio/dataexp/service/export/strategies/InstancesExportStrategyTest.java
[MDEXP-775](https://folio-org.atlassian.net/browse/MDEXP-775) - Exporting deleted MARC instances have modified ldr05 and 005
The exported MARC records  using /export-deleted do not have ldr05 ="d" and 005 differs from the original record as well.
Add DELETED state. …
=> MDEXP-775 - Exporting deleted MARC instances have modified ldr05 and 005 

src/main/java/org/folio/dataexp/service/InputFileProcessor.java, src/main/java/org/folio/dataexp/service/export/strategies/AbstractExportStrategy.java, src/main/java/org/folio/dataexp/service/export/strategies/HoldingsExportAllStrategy.java, src/main/java/org/folio/dataexp/service/export/strategies/HoldingsExportStrategy.java, src/main/java/org/folio/dataexp/service/export/strategies/HoldingsItemsResolverService.java, src/main/java/org/folio/dataexp/service/export/strategies/InstancesExportStrategy.java, src/main/java/org/folio/dataexp/service/export/strategies/rule/builder/TransformationRuleBuilder.java, src/main/java/org/folio/dataexp/util/ErrorCode.java, src/test/java/org/folio/dataexp/service/export/strategies/HoldingsItemsResolverServiceTest.java
[MDEXP-770](https://folio-org.atlassian.net/browse/MDEXP-770) - Provide missing error messages and clean up existing errors for data export
Provide missing error messages and clean up existing errors for data export
* Updated ErrorCode enum
* Fixed duplicated error messages
Ideally all of the PRs involved in breaking changes would be merged in the same …
=> MDEXP-770 - Provide missing error messages and clean up existing errors for data export

src/main/java/org/folio/dataexp/service/export/strategies/AuthorityExportStrategy.java
[MDEXP-681](https://folio-org.atlassian.net/browse/MDEXP-681) - Ability to export deleted MARC authority records - support in ECS environment
Ability to export deleted MARC authority records - support in ECS environment
Add handle deleted to ECS. …
=> MDEXP-681 - Ability to export deleted MARC authority records - support in ECS environment

src/main/resources/db/changelog/changelog-master.xml, src/main/resources/db/changelog/changes/add_default_deleted_authority_job_profile.sql, src/main/resources/db/changelog/changes/add_default_deleted_authority_job_profile.xml
[MDEXP-758](https://folio-org.atlassian.net/browse/MDEXP-758) - Deleted authority export job profile is absent …
=> MDEXP-758 - Deleted authority export job profile is absent

src/main/java/org/folio/dataexp/service/export/strategies/InstancesExportAllStrategy.java, src/main/java/org/folio/dataexp/util/ErrorCode.java, src/test/java/org/folio/dataexp/service/export/strategies/InstancesExportAllStrategyTest.java
Follow up PR to [#495](https://github.com/folio-org/mod-data-export/pull/495) with error message fixing.
=> MDEXP-748 - Export all - Handle error details of bad data records

src/main/java/org/folio/dataexp/service/export/strategies/AuthorityExportStrategy.java
[MDEXP-764](https://folio-org.atlassian.net/browse/MDEXP-764) - Export with the file containing mix of deleted and not deleted authorities ids stuck in Progress or executed for long time 
Speed up the export of authorities.
Get the errors from DB only once for each slice at the beginning of handling deleted.
Ideally all of the PRs involved in breaking …
=> MDEXP-764 - Export with the file containing mix of deleted and not deleted authorities ids stuck in Progress or executed for long time 

pom.xml, src/main/resources/rules/rulesDefault.json
[MDEXP-785](https://folio-org.atlassian.net/browse/MDEXP-785) - Set LDR05 to "d" for records set for deletion
When a FOLIO instance is set for deletion and the exported MARC  is generated on the fly, LDR05 should be set to “d”.
* Upgraded GMU version
* Updated default rules
Ideally all of the PRs involved in breaking changes would be merged in the same …
=> MDEXP-785 - Set LDR05 to "d" for records set for deletion

descriptors/ModuleDescriptor-template.json
=> MDEXP-796 API version update

src/main/java/org/folio/dataexp/service/export/strategies/InstancesExportAllStrategy.java, src/test/java/org/folio/dataexp/service/DataExportAllServiceTest.java
[MDEXP-793](https://folio-org.atlassian.net/browse/MDEXP-793) - Export all - Set LDR05 to "d" for records set for deletion
* Removed processing of deleted via API instances
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment.  Communication is paramount …
=> MDEXP-793 - Export all - Set LDR05 to "d" for records set for deletion

NEWS.md, descriptors/ModuleDescriptor-template.json
[MDEXP-801](https://folio-org.atlassian.net/browse/MDEXP-801)
Upgrade the API version in the ModuleDescriptor-template.json:
- `holdings-storage 8.0` …
=> MDEXP-801 - Upgrade the API version in the ModuleDescriptor-template.json

NEWS.md, descriptors/ModuleDescriptor-template.json
[MDEXP-797](https://folio-org.atlassian.net/browse/MDEXP-797)
According to the epic https://folio-org.atlassian.net/browse/FOLIO-4044, some permissions have been changed in the mod-source-record-storage.
mod-data-export-worker uses the permission `source-storage.sourceRecords.get` for `source-storage/stream/marc-record-identifiers` endpoint
It should be replaced with `source-storage.stream.marc-record-identifiers.collection.post` from `source-storage-source-records v3.2`
- Do …
=> MDEXP-797 Update source-storage-source-records to v3.2 and rename module permission

descriptors/ModuleDescriptor-template.json, src/main/java/org/folio/dataexp/client/PermissionsSelfCheckClient.java, src/main/java/org/folio/dataexp/client/UserPermissionsClient.java, src/main/java/org/folio/dataexp/controllers/PermissionsSelfCheckController.java, src/main/java/org/folio/dataexp/domain/dto/UserPermissions.java, src/main/java/org/folio/dataexp/exception/permissions/check/ViewPermissionDoesNotExist.java, src/main/java/org/folio/dataexp/service/export/strategies/HoldingsExportAllStrategy.java, src/main/java/org/folio/dataexp/service/export/strategies/HoldingsExportStrategy.java, src/main/java/org/folio/dataexp/service/export/strategies/HoldingsItemsResolverService.java, src/main/java/org/folio/dataexp/service/permissions/PermissionsProvider.java, src/main/java/org/folio/dataexp/service/permissions/RequiredPermissionResolver.java, src/main/java/org/folio/dataexp/service/validators/PermissionsValidator.java, src/main/java/org/folio/dataexp/util/Constants.java, src/main/java/org/folio/dataexp/util/ErrorCode.java, src/main/resources/swagger.api/data-export.yaml, src/test/java/org/folio/dataexp/controllers/PermissionsSelfCheckControllerTest.java, src/test/java/org/folio/dataexp/service/export/strategies/HoldingsExportStrategyTest.java, src/test/java/org/folio/dataexp/service/export/strategies/HoldingsItemsResolverServiceTest.java, src/test/java/org/folio/dataexp/service/permissions/PermissionsProviderTest.java, src/test/java/org/folio/dataexp/service/permissions/RequiredPermissionResolverTest.java, src/test/java/org/folio/dataexp/service/validators/PermissionsValidatorTest.java
[MDEXP-786](https://folio-org.atlassian.net/browse/MDEXP-786) - Export Holdings and Items with Custom Export Profile from Central Tenant - Permissions handling 
The central tenant should be able to shared instances enriched with holdings and items records using the custom export profile.
Add permissions self-check.
Ideally all of the PRs involved in …
=> MDEXP-786 - Export Holdings and Items with Custom Export Profile from Central Tenant - Permissions handling

README.md, descriptors/ModuleDescriptor-template.json, src/main/java/org/folio/dataexp/client/EurekaUserPermissionsClient.java, src/main/java/org/folio/dataexp/client/OkapiUserPermissionsClient.java, src/main/java/org/folio/dataexp/controllers/PermissionsSelfCheckController.java, src/main/java/org/folio/dataexp/domain/dto/UserPermissions.java, src/main/java/org/folio/dataexp/service/UserPermissionsService.java, src/main/resources/application.yml, src/test/java/org/folio/dataexp/controllers/PermissionsSelfCheckControllerTest.java, src/test/java/org/folio/dataexp/service/UserPermissionsServiceTest.java
[MDEXP-802](https://folio-org.atlassian.net/browse/MDEXP-802) - Support Eureka permissions model for data export
Implement logic to support permissions from mod-roles-keycloak and integrate it in existing approach 
Introduce an environment variable in the module configuration that will be specifically depend to the environment to switch logic between mod-permissions and mod-roles-keycloa
- Are the JIRAs under active development? …
=> MDEXP-802 - eureka permission model

NEWS.md, pom.xml
=> FOLIO-4101 -  Release 5.1.0

src/main/java/org/folio/dataexp/util/FolioExecutionContextUtil.java
=> MDEXP-810 use okapi headers from spring-base

NEWS.md, pom.xml
=> Release 5.1.1

NEWS.md, pom.xml
=> Release 5.1.2

descriptors/ModuleDescriptor-template.json, src/main/java/org/folio/dataexp/controllers/PermissionsSelfCheckController.java, src/main/java/org/folio/dataexp/service/permissions/PermissionsProvider.java, src/main/java/org/folio/dataexp/service/validators/PermissionsValidator.java, src/test/java/org/folio/dataexp/service/permissions/PermissionsProviderTest.java
=> EUREKA-529 - avoid self invocation

NEWS.md, pom.xml
=> Release 5.1.3

src/main/java/org/folio/dataexp/repository/JobProfileEntityRepository.java, src/main/java/org/folio/dataexp/service/DataExportAllService.java, src/main/java/org/folio/dataexp/service/QuickExportService.java, src/main/java/org/folio/dataexp/util/Constants.java, src/test/java/org/folio/dataexp/service/DataExportAllServiceTest.java
[MDEXP-817](https://folio-org.atlassian.net/browse/MDEXP-817) - Deleted authority export job profile is displayed for Export all authorities done without specifying profile id on Eureka environment
When export all authorities request doesn’t include profile id in the body - Deleted authority export job profile is displayed as the profile for such export all.
Add 'Default' to the query.
- …
=> MDEXP-817 - Deleted authority export job profile is displayed for Export all authorities done without specifying profile id on Eureka environment

descriptors/ModuleDescriptor-template.json
=> Add missing interfaces

NEWS.md, descriptors/ModuleDescriptor-template.json, pom.xml, src/main/java/org/folio/dataexp/repository/JobProfileEntityRepository.java, src/main/java/org/folio/dataexp/service/DataExportAllService.java, src/main/java/org/folio/dataexp/service/QuickExportService.java, src/main/java/org/folio/dataexp/util/Constants.java, src/test/java/org/folio/dataexp/service/DataExportAllServiceTest.java
Release 5.1.4
While it's helpful for reviewers to help identify potential problems, …
=> Release 5.1.4

pom.xml
[MDEXP-818](https://folio-org.atlassian.net/browse/MDEXP-818) - Upgrade deps fixing vulnerabilities for Ramsons
Updating dependencies …
=> MDEXP-818 - Upgrade deps fixing vulnerabilities for Ramsons

NEWS.md, pom.xml
=> Release 5.1.5

src/main/java/org/folio/dataexp/service/export/strategies/HoldingsExportStrategy.java, src/main/java/org/folio/dataexp/service/export/strategies/HoldingsItemsResolverService.java, src/main/java/org/folio/dataexp/service/export/strategies/InstancesExportStrategy.java, src/main/java/org/folio/dataexp/util/ErrorCode.java, src/test/java/org/folio/dataexp/service/export/strategies/HoldingsItemsResolverServiceTest.java
[MODEXP-805](https://folio-org.atlassian.net/browse/MDEXP-805) - Issues with errors "error.noAffiliation" and “error.instance.noPermission” when export Instances from Central tenant
In MDEXP-786: Export Holdings and Items with Custom Export Profile from Central Tenant - Permissions handling
CLOSED
some logic was implemented to handle "error.noAffiliation" and “error.instance.noPermission” errors when export Instances with Custom profile from Central tenant
However, the following issues should be fixed to meet requirements to the errors described here [Affiliation and Permissions Handling in Data Export](https://folio-org.atlassian.net/wiki/spaces/FOLIJET/pages/486440983/Affiliation+and+Permissions+Handling+in+Data+Export)
* Logic improvements
Before merging this PR, …
=> MODEXP-805 - Issues with errors "error.noAffiliation" and “error.instance.noPermission” when export Instances from Central tenant

NEWS.md, descriptors/ModuleDescriptor-template.json, pom.xml
=> Release 5.1.6

src/main/java/org/folio/dataexp/service/InputFileProcessor.java, src/test/java/org/folio/dataexp/service/InputFileProcessorTest.java, src/test/resources/upload_with_bom.csv
[MDEXP-824](https://folio-org.atlassian.net/browse/MDEXP-824) - First Instance UUID record from .csv file with "UTF-8 with BOM" encoding is processed as error in Data export 
When uploading a .csv file containing Instances UUIDs with "UTF-8 with BOM" encoding for Data export, the first record from the file is processed as error.
Remove BOM from identifier string.
- Do PRs exist for these …
=> MDEXP-824 - First Instance UUID record from .csv file with "UTF-8 with BOM" encoding is processed as error in Data export 

Dockerfile, Jenkinsfile, descriptors/ModuleDescriptor-template.json, pom.xml, src/test/java/org/folio/dataexp/BaseDataExportInitializer.java, src/test/java/org/folio/dataexp/controllers/DataExportAllControllerTest.java, src/test/java/org/folio/dataexp/controllers/DataExportAuthorityDeletedControllerTest.java, src/test/java/org/folio/dataexp/controllers/DataExportControllerTest.java, src/test/java/org/folio/dataexp/controllers/DataExportDeletedMarcIdsControllerTest.java, src/test/java/org/folio/dataexp/controllers/DownloadRecordControllerTest.java, src/test/java/org/folio/dataexp/controllers/FileDefinitionsControllerTest.java, src/test/java/org/folio/dataexp/controllers/JobExecutionsControllerTest.java, src/test/java/org/folio/dataexp/controllers/JobProfileControllerTest.java, src/test/java/org/folio/dataexp/controllers/LogsControllerTest.java, src/test/java/org/folio/dataexp/controllers/MappingProfileControllerTest.java, src/test/java/org/folio/dataexp/controllers/QuickExportControllerTest.java, src/test/java/org/folio/dataexp/controllers/TransformationFieldsControllerTest.java, src/test/java/org/folio/dataexp/service/DataExportServiceTest.java, src/test/java/org/folio/dataexp/service/DownloadRecordTest.java, src/test/java/org/folio/dataexp/service/InputFileProcessorTest.java, src/test/java/org/folio/dataexp/service/ServiceInitializer.java, src/test/java/org/folio/dataexp/service/SingleFileProcessorTest.java, src/test/java/org/folio/dataexp/service/SlicerProcessorTest.java, src/test/java/org/folio/dataexp/service/TimerServiceTest.java, src/test/java/org/folio/dataexp/service/export/strategies/AuthorityExportStrategyTest.java
[MDEXP-826](https://folio-org.atlassian.net/browse/MDEXP-826) - Update to mod-data-export Java 21
Upgrading Java version to Java 21. …
=> MDEXP-826 - Update to mod-data-export Java 21

NEWS.md, pom.xml
[MDEXP-828](https://folio-org.atlassian.net/browse/MDEXP-828) - Release 5.2.0
=> MDEXP-828 - Release 5.2.0

descriptors/ModuleDescriptor-template.json, src/main/resources/application.yml
Improving connection pool size, making it configurable by DB_MAXPOOLSIZE.
While it's …
=> Connection pool size improvements

NEWS.md, pom.xml
Release 5.2.1.
Release v5.2.1. …
=> Release 5.2.1

src/main/java/org/folio/dataexp/service/export/strategies/HoldingsExportStrategy.java
=> MDEXP-843 clean up logs

NEWS.md, pom.xml
Release v5.1.7
While it's helpful for reviewers to help identify potential problems, …
=> Release v5.1.7 (Ramsons)

NEWS.md, pom.xml
Release v5.2.2
While it's helpful for reviewers to help identify potential problems, …
=> Release v5.2.2

src/main/java/org/folio/dataexp/service/validators/DataExportRequestValidator.java, src/test/java/org/folio/dataexp/service/validators/DataExportRequestValidatorTest.java
[MDEXP-836](https://folio-org.atlassian.net/browse/MDEXP-836) - BE - Export authority records using CQL
Authority records can be exported based on the saved .cql file.
* Improved authority validator to allow CQL files …
=> MDEXP-836 - BE - Export authority records using CQL

.github/dependabot.yml
=> MDEXP-846 setup dependabot

descriptors/ModuleDescriptor-template.json
=> MDEXP-850 bump up item-storage

descriptors/ModuleDescriptor-template.json, pom.xml, src/main/java/org/folio/dataexp/ModDataExportApplication.java, src/main/java/org/folio/dataexp/client/QueryClient.java, src/main/java/org/folio/dataexp/service/QueryService.java, src/main/java/org/folio/dataexp/service/export/strategies/ld/LinkedDataConverter.java, src/main/java/org/folio/dataexp/service/export/strategies/ld/LinkedDataProvider.java, src/test/java/org/folio/dataexp/service/ServiceInitializer.java, src/test/java/org/folio/dataexp/service/export/strategies/ld/LinkedDataConverterTest.java, src/test/java/org/folio/dataexp/service/export/strategies/ld/LinkedDataProviderTest.java
As part of [UXPROD-4586](https://folio-org.atlassian.net/browse/UXPROD-4586) to add Linked Data export via FQM, add a basic Feign FQM client. Also add all new dependencies to pom.xml.
https://folio-org.atlassian.net/browse/MDEXP-862
Utilize Feign to make a client that makes use of select FQM endpoints. Include FQM in module dependencies list, update pom.xml (including upcoming Linked Data library not utilized in this PR).
I intend to keep this feature work as disconnected as possible from the existing code base until integration is needed, both within the code and by using a short-term feature branch kept up to date with master, meant to be merged after feature implementation is complete.
- Does …
=> MDEXP-862: Add FQM client
